### ISSUE TITLE
[data grid] `getTreeDataPath` not working in hosting version

### ISSUE THREAD

**Issue by AnatoliiCubex** [mui/mui-x#10554]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

 Im using data tree im DataGridPro component to see "accordions" in table, everything works in my localhost, but in deployed version to firebase hosting(using Google Chrome browser) the website crushes, here is the code: 
 
  ```
const getHierarchicalPath = (row: IPromotionRaw): string[] => {
    const path: string[] = [];
    let currentRow: IPromotionRaw | null = row;

    const findParentRow = (parentId: number | null): IPromotionRaw | null =>
      Promotions?.data.find((r) => r.id === parentId) || null;

    while (currentRow) {
      path.unshift(currentRow.id.toString());
      currentRow = findParentRow(currentRow?.parent_id);
    }

    return path;
  };

  const getTreeDataPath: DataGridProProps['getTreeDataPath'] = (row) => {
    return getHierarchicalPath(row);
  };


<StyledDataGridPro
            treeData
            getTreeDataPath={getTreeDataPath}
...rest/>
```

### Current behavior 😯

Im receiving this error in browser:

```
referenceError: _i is not defined
    at D (buildRowTree.js:153:23)
    at s.useCallback.rows (buildRowTree.js:150:41)
    at useGridTreeDataPreProcessors.js:86:12
    at Object.unstable_applyStrategyProcessor (useGridStrategyProcessing.js:94:34)
    at VA.s.useCallback.e.current.o.forEach.e.current.hasOwnProperty.e.current.<computed> [as unstable_applyStrategyProcessor] (useGridApiMethod.js:14:84)
    at kO (gridRowsUtils.js:57:43)
    at TO (useGridRows.js:20:11)
    at wP (useGridInitializeState.js:6:28)
    at d_ (useDataGridProComponent.js:46:3)
    at DataGridPro.js:16:18
```

![image](https://github.com/mui/material-ui/assets/117375666/7bd3ed23-0e22-4a0c-b11d-2bf7e40f012a)

**Search keywords**:

**Comment by DanailH** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by AnatoliiCubex** [comment]
> Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 . A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!

the link you provided is not working for me (actually, whole codesandbox is not working while trying to setup some project), is there any analog to show the example? I cant record my react app because its a commercial project

But the test case is simple, I just receive data from endpoint and pass it to data grid component, it worked last week but few days ago it starts crashing the whole website

**Comment by DanailH** [comment]
@AnatoliiCubex I tried the link for the codesandbox and it seems to be working, please try again. We can't investigate if there is no reproduction provided.

**Comment by AnatoliiCubex** [comment]
> @AnatoliiCubex I tried the link for the codesandbox and it seems to be working, please try again. We can't investigate if there is no reproduction provided.

Please try this code, somehow I have an error in codesandbox, but I managed to change default code

```
import React from "react";
import { DataGrid, GridRowsProp, GridColumns } from "@mui/x-data-grid";

interface IPromotionRaw {
  type: string;
  is_active: boolean;
  title: string | null;
  updated_at: string;
  addressable_path: string | null;
  thumbnail_addressable_path: string | null;
  shop_addressable_path: string | null;
  id: number;
  parent_id: number | null;
  availability: number;
  created_at: string;
  deposit_bundle_id: string;
  status: string;
  is_draft: boolean;
  usd: number;
  bonus: number;
  gems: number;
  // parent_id: number;
}

const rows: GridRowsProp = [
  {
    "updated_at": "2023-06-21T11:04:19.630960",
    "progress_bar_addressable_path": null,
    "addressable_path": null,
    "button_text": null,
    "shop_addressable_path": null,
    "status": "ended",
    "title": "parallel parent",
    "thumbnail_addressable_path": null,
    "id": 2127,
    "type": "challenge",
    "is_draft": false,
    "parent_id": null,
    "availability": null,
    "completion_order": null,
    "is_active": true,
    "sub_type": "parallel",
    "created_at": "2023-06-14T07:14:04.840380",
    "parameters": {
      "pt_id": 333
    }
  },
  {
    "updated_at": "2023-06-14T07:17:18.246239",
    "progress_bar_addressable_path": null,
    "addressable_path": null,
    "button_text": null,
    "shop_addressable_path": null,
    "status": "ended",
    "title": "clear board parallel child",
    "thumbnail_addressable_path": null,
    "id": 2128,
    "type": "challenge",
    "is_draft": false,
    "parent_id": 2127,
    "availability": null,
    "completion_order": null,
    "is_active": true,
    "sub_type": "clear_board",
    "created_at": "2023-06-14T07:14:04.840380",
    "parameters": null
  },
  {
    "updated_at": "2023-06-14T07:17:18.246239",
    "progress_bar_addressable_path": null,
    "addressable_path": null,
    "button_text": null,
    "shop_addressable_path": null,
    "status": "ended",
    "title": "play var tour parallel child",
    "thumbnail_addressable_path": null,
    "id": 2129,
    "type": "challenge",
    "is_draft": false,
    "parent_id": 2127,
    "availability": null,
    "completion_order": null,
    "is_active": true,
    "sub_type": "play_various_tournaments",
    "created_at": "2023-06-14T07:14:04.840380",
    "parameters": null
  },
  {
    "updated_at": "2023-08-28T13:58:39.373977",
    "progress_bar_addressable_path": null,
    "addressable_path": "journey_challenge/journey_challenge_main.prefab",
    "button_text": null,
    "shop_addressable_path": null,
    "status": "ended",
    "title": "journey parent updated",
    "thumbnail_addressable_path": "journey_challenge/journey_challenge_thumb_narrow.prefab",
    "id": 2222,
    "type": "challenge",
    "is_draft": false,
    "parent_id": null,
    "availability": null,
    "completion_order": null,
    "is_active": true,
    "sub_type": "journey_free_players",
    "created_at": "2023-06-18T07:55:04.221615",
    "parameters": null
  },
  {
    "updated_at": "2023-08-28T13:58:39.475760",
    "progress_bar_addressable_path": null,
    "addressable_path": null,
    "button_text": null,
    "shop_addressable_path": null,
    "status": "ended",
    "title": "Child 1 - journey_free_players",
    "thumbnail_addressable_path": null,
    "id": 2223,
    "type": "challenge",
    "is_draft": false,
    "parent_id": 2222,
    "availability": null,
    "completion_order": 1,
    "is_active": true,
    "sub_type": "journey_free_players",
    "created_at": "2023-06-18T07:55:04.221615",
    "parameters": null
  },
  {
    "updated_at": "2023-08-28T13:58:39.467110",
    "progress_bar_addressable_path": null,
    "addressable_path": null,
    "button_text": null,
    "shop_addressable_path": null,
    "status": "ended",
    "title": "Child 2 - journey_free_players",
    "thumbnail_addressable_path": null,
    "id": 2224,
    "type": "challenge",
    "is_draft": false,
    "parent_id": 2222,
    "availability": null,
    "completion_order": 2,
    "is_active": true,
    "sub_type": "journey_free_players",
    "created_at": "2023-06-18T07:55:04.221615",
    "parameters": null
  },
  {
    "updated_at": "2023-08-28T13:58:39.354228",
    "progress_bar_addressable_path": null,
    "addressable_path": null,
    "button_text": null,
    "shop_addressable_path": null,
    "status": "ended",
    "title": "Child 3 - journey_free_players",
    "thumbnail_addressable_path": null,
    "id": 2225,
    "type": "challenge",
    "is_draft": false,
    "parent_id": 2222,
    "availability": null,
    "completion_order": 3,
    "is_active": true,
    "sub_type": "journey_free_players",
    "created_at": "2023-06-18T07:55:04.221615",
    "parameters": null
  },
  {
    "updated_at": "2023-08-28T07:20:33.632633",
    "progress_bar_addressable_path": null,
    "addressable_path": "gems_bay_v4/gems_bay_v4_main.prefab",
    "button_text": null,
    "shop_addressable_path": null,
    "status": "running",
    "title": "Play gems bay",
    "thumbnail_addressable_path": "gems_bay_v4/gems_bay_v4_thumb_narrow.prefab",
    "id": 2404,
    "type": "challenge",
    "is_draft": false,
    "parent_id": null,
    "availability": null,
    "completion_order": null,
    "is_active": true,
    "sub_type": "play_a_specific_tournament",
    "created_at": "2023-06-22T13:30:58.088196",
    "parameters": {
      "pt_id": 13
    }
  },
  {
    "updated_at": "2023-07-04T07:30:00.548497",
    "progress_bar_addressable_path": null,
    "addressable_path": "gems_bay/gems_bay_main.prefab",
    "button_text": null,
    "shop_addressable_path": null,
    "status": "cooling_down",
    "title": "Play gems bay",
    "thumbnail_addressable_path": "gems_bay/gems_bay_thumb_narrow.prefab",
    "id": 2667,
    "type": "challenge",
    "is_draft": false,
    "parent_id": null,
    "availability": null,
    "completion_order": null,
    "is_active": false,
    "sub_type": "score_more_than_specific_tournament",
    "created_at": "2023-07-04T07:30:00.548497",
    "parameters": {
      "pt_id": 13,
      "score": 3000
    }
  },
  {
    "updated_at": "2023-08-03T10:24:37.594342",
    "progress_bar_addressable_path": null,
    "addressable_path": "testChallange4/testChallange4_main.prefab",
    "button_text": null,
    "shop_addressable_path": null,
    "status": "ended",
    "title": "testChallange5",
    "thumbnail_addressable_path": null,
    "id": 2744,
    "type": "challenge",
    "is_draft": false,
    "parent_id": null,
    "availability": null,
    "completion_order": null,
    "is_active": false,
    "sub_type": "play_a_specific_tournament",
    "created_at": "2023-07-05T14:18:48.823060",
    "parameters": {
      "pt_id": 1432
    }
  }
];

const columns: GridColumns[] = [
  {
    "field": "type",
    "headerName": "Type",
    "flex": 1
  },
  {
    "field": "title",
    "headerName": "Title",
    "flex": 1
  },
  {
    "field": "created_at",
    "headerName": "Created at",
    "flex": 1
  },
  {
    "field": "creatiives",
    "headerName": "Creatives",
    "flex": 1
  },
  {
    "field": "schedule",
    "headerName": "Schedule",
    "flex": 1,
    "sortable": false,
    "filterable": false
  },
  {
    "field": "actions",
    "type": "actions",
    "headerName": "Actions",
    "width": 100
  },
  {
    "field": "edit",
    "headerName": "",
    "width": 60,
    "align": "center",
    "sortable": false,
    "filterable": false
  },
  {
    "field": "status",
    "headerName": "Status",
    "flex": 1
  }
];

const getHierarchicalPath = (row: IPromotionRaw): string[] => {
  const path: string[] = [];
  let currentRow: IPromotionRaw | null = row;

  const findParentRow = (parentId: number | null): IPromotionRaw | null =>
    // @ts-ignore
    Promotions ?.data.find((r) => r.id === parentId) || null;

  while (currentRow) {
    path.unshift(currentRow.id.toString());
    currentRow = findParentRow(currentRow ?.parent_id);
  }

  return path;
};

const getTreeDataPath: DataGridProProps['getTreeDataPath'] = (row) => {
  return getHierarchicalPath(row);
};

export default function App() {
  return (
    <div style={{ height: 300, width: "100%" }}>
      <DataGrid rows={rows} columns={columns} treeData getTreeDataPath={getTreeDataPath}/>
    </div>
  );
}
```

**Comment by DanailH** [comment]
```
ReferenceError
Promotions is not defined
```

You can create a codesandbox yourself if the link is not working for you.

**Comment by AnatoliiCubex** [comment]
> ```
> ReferenceError
> Promotions is not defined
> ```
> 
> You can create a codesandbox yourself if the link is not working for you.

thats the case, I cant even create my own project in codesandbox, but the error you have is fixible, please change `getHierarchicalPath` code to this:

```
const getHierarchicalPath = (row: IPromotionRaw): string[] => {
  const path: string[] = [];
  let currentRow: IPromotionRaw | null = row;

  const findParentRow = (parentId: number | null): IPromotionRaw | null =>
    // @ts-ignore
    rows.find((r) => r.id === parentId) || null;

  while (currentRow) {
    path.unshift(currentRow.id.toString());
    currentRow = findParentRow(currentRow ?.parent_id);
  }

  return path;
};
```

**Comment by romgrk** [comment]
@AnatoliiCubex You can use any alternative that works for you, for example https://stackblitz.com/.

**Comment by AnatoliiCubex** [comment]
> @AnatoliiCubex You can use any alternative that works for you, for example https://stackblitz.com/fork/github/mui/mui-x/tree/master/templates/x-data-grid

Thank you for providing another online code editor, I made project but it works here
https://stackblitz.com/edit/stackblitz-starters-c5pcxr?file=src%2FApp.tsx

But as I wrote in first post, I receive an error in my hosted version

```
referenceError: _i is not defined
    at D (buildRowTree.js:153:23)
    at s.useCallback.rows (buildRowTree.js:150:41)
    at useGridTreeDataPreProcessors.js:86:12
    at Object.unstable_applyStrategyProcessor (useGridStrategyProcessing.js:94:34)
    at VA.s.useCallback.e.current.o.forEach.e.current.hasOwnProperty.e.current.<computed> [as unstable_applyStrategyProcessor] (useGridApiMethod.js:14:84)
    at kO (gridRowsUtils.js:57:43)
    at TO (useGridRows.js:20:11)
    at wP (useGridInitializeState.js:6:28)
    at d_ (useDataGridProComponent.js:46:3)
    at DataGridPro.js:16:18
    ```

**Comment by AnatoliiCubex** [comment]
As I found out in google, this problem is more related to building my react app rather than error in library code, anyone knows how to fix it?

**Comment by AnatoliiCubex** [comment]
If someone will bump into this problem, deleting `node_modules`&`package-lock.json` and running `npm install` helped me
