### ISSUE TITLE
[charts] Support of different series values arrays lengths in terms of line chart

### ISSUE THREAD

**Issue by typical000** [mui/mui-x#10785]
### Summary 💡

I wondered if it's more a bug than a feature request, but seems that this feature is not implemented.

*Feature in a nutshell:*
Allow to pass different arrays of values for `series` in terms of length, allowing to draw non-complete lines.

For now, it seems that's (at least what I saw after the codebase examination) impossible since I'm getting an error like:
```
Warning: Failed prop type: The prop `ownerState.y` is marked as required in `MuiMarkElementRoot`, but its value is `undefined`.
    at eval (https://nt4j42.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at MarkElement (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/LineChart/MarkElement.js:73:13)
    at g
    at MarkPlot (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/LineChart/MarkPlot.js:29:17)
    at svg
    at eval (https://nt4j42.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at ChartsSurface (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/ChartsSurface.js:22:20)
    at HighlightProvider (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/context/HighlightProvider.js:40:39)
    at InteractionProvider (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/context/InteractionProvider.js:42:41)
    at CartesianContextProvider (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/context/CartesianContextProvider.js:49:43)
    at SeriesContextProvider (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/context/SeriesContextProvider.js:59:41)
    at DrawingProvider (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/context/DrawingProvider.js:33:34)
    at ChartContainer (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/ChartContainer/index.js:19:17)
    at div
    at eval (https://nt4j42.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at ResponsiveChartContainer (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/ResponsiveChartContainer/index.js:101:17)
    at LineChart (https://nt4j42.csb.app/node_modules/@mui/x-charts/esm/LineChart/LineChart.js:35:17)
    at div
    at Demo
    at StyledEngineProvider (https://nt4j42.csb.app/node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:22:23)
```
And nothing renders, only the X and Y axis. Also found this non-production error: https://github.com/mui/mui-x/blob/master/packages/x-charts/src/LineChart/LinePlot.tsx#L74

*More details and why this Feature Request was created*
I'm building a comparison chart between years (e.g. 2022 and 2023), and, in the case of the 2023 year - I can't get any data from the future. The only +- adequate solution I found is filling the missing month with zero. But, our design team and I are not too fond of the behavior when a chart goes to zero. It suggests that something went wrong. And there is no option to interrupt a line since the path is generated as one `<path>` tag.

So I had in my mind something, as a workaround, like this:
1. Use `stroke-dashoffset` and `stroke-dasharray` and interrupt the line at some point. But the problem is that I can't calculate the `length` of the line from the outside and need to recreate the entire `LineChart` with `ResponsiveChartContainer`, etc., and things are going harder if we use curves inside lines.
3. Create 2 overlapping charts. But it is not possible since we'll break any interaction with the chat, which is located under another, and also, we can't do so since we can't create an X axis longer than the provided data (https://github.com/mui/mui-x/blob/master/packages/x-charts/src/LineChart/LinePlot.tsx#L74)

### Examples 🌈

Please see this example: 
https://codesandbox.io/s/line-chart-x-charts-highcharts-comparison-nt4j42?file=/src/Demo.tsx:0-1873

I prepared here:
1. A non-working example using X-charts (with non-equal series value lengths)
2. A working example using X-chars (the only possible way to do so, is adding zeros as a tail and getting a chart dropping)
3. An example of what I'm looking for, but using Highcharts.

### Motivation 🔦

Seems like other chart libraries support this behavior.

**Search keywords**: line chart different series values array lengths

**Comment by LukasTy** [comment]
Thank you for creating this issue! 🙏 
This is clearly an actual shortcoming in the existing implementation that will be addressed. 😉

**Comment by alexfauquette** [comment]
Thanks for the issue, it's been reported in StackOverflow and discord, but issues is the best place :+1:

Yes, that's in the roadmap for the coming weeks. The idea I've in mind is to allow passing `null` as a value if there is no value to plot. A second step could be to consider that if series have fewer data than the axis, they should simply stop.
