### ISSUE TITLE
[DatePicker] Prop disableUnderline: true set off ForwardRef error

### ISSUE THREAD

**Issue by michaelfr** [mui/mui-x#11410]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/elegant-cohen-p296k5

The problem is not reproductable in codesandbox

Steps:
-  set disableUnderline to true

### Current behavior

with variant="standard" and disableUnderline: true, there is this errors in Console : 

```
The above error occurred in the <ForwardRef(TextField)> component:
    in ForwardRef(TextField) (created by ForwardRef(DateField))
    in ForwardRef(DateField) (created by ForwardRef(DesktopDatePicker))
    in LocalizationProvider (created by ForwardRef(DesktopDatePicker))
    in ForwardRef(DesktopDatePicker) (created by ForwardRef(DatePicker))

Uncaught TypeError: ReactDebugCurrentFrame.setExtraStackFrame is not a function
    at setCurrentlyValidatingElement (react-jsx-runtime.development.js:574:1)
    at checkPropTypes (react-jsx-runtime.development.js:618:1)
    at validatePropTypes (react-jsx-runtime.development.js:1072:1)
    at jsxWithValidation (react-jsx-runtime.development.js:1192:1)
    at jsxWithValidationDynamic (react-jsx-runtime.development.js:1209:1)
    at TextField (TextField.js:150:1)

```

### Expected behavior

no error

### Context

I try to have no border and underline in a datePicker 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 14.1.1
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.26 
    @mui/core-downloads-tracker:  5.14.20 
    @mui/icons-material: ^5.14.19 => 5.14.19 
    @mui/lab: ^5.0.0-alpha.155 => 5.0.0-alpha.155 
    @mui/material: ^5.14.20 => 5.14.20 
    @mui/private-theming:  5.14.20 
    @mui/styled-engine:  5.14.20 
    @mui/styles: ^5.14.20 => 5.14.20 
    @mui/system:  5.14.20 
    @mui/types:  7.2.10 
    @mui/utils:  5.14.20 
    @mui/x-date-pickers: ^6.18.3 => 6.18.3 
    @types/react:  17.0.0 
    react: ^17.0.0 => 17.0.2 
    react-dom: ^16.14.0 => 16.14.0
```
</details>

**Search keywords**: x-date-picker disableUnderline

**Comment by michelengelen** [comment]
Hey @michaelfr ... I tried to reproduce this as well, but couldn't get the error to show up.
Could you check your implementation if there is anything missing?

I tried to reproduce the bug with other field implementations as well, but couldn't get it to show up.
