### ISSUE TITLE
Type Error with AdapterLuxon

### ISSUE THREAD

**Issue by harry-peirse-jfc** [mui/mui-x#11853]
### Search keywords

DateTime Typescript AdapterLuxon Error

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

[Link to live example](https://codesandbox.io/p/devbox/9kn6pv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clryscval00063b6f3pkphl20%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clryscvak00023b6fdkhxkzuj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clryscvak00033b6fqztguzco%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clryscvak00053b6fidubva9o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clryscvak00023b6fdkhxkzuj%2522%253A%257B%2522id%2522%253A%2522clryscvak00023b6fdkhxkzuj%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clrysvoca00m83b6f0360ajqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrysvoca00m83b6f0360ajqa%2522%257D%252C%2522clryscvak00053b6fidubva9o%2522%253A%257B%2522id%2522%253A%2522clryscvak00053b6fidubva9o%2522%252C%2522activeTabId%2522%253A%2522clryst7e700b23b6fol21z7cq%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clryst7e700b23b6fol21z7cq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clryscvak00033b6fqztguzco%2522%253A%257B%2522id%2522%253A%2522clryscvak00033b6fqztguzco%2522%252C%2522activeTabId%2522%253A%2522clrysxaq900xr3b6f3ortfdxe%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clryss40h00573b6fzaxh3buw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clryss46t000ke7go89ia2tif%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clryst1cn009g3b6f98zg4wmz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clrysxaq900xr3b6f3ortfdxe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrysxawr000te7go7pemeb3j%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1.  Run tsc --noEmit in the terminal
2. Error appears

### Current behavior

It is standard practice in Luxon to write the following when invalid dates should throw errors:

```
import { Settings } from "luxon";

Settings.throwOnInvalid = true;

declare module "luxon" {
  interface TSSettings {
    throwOnInvalid: true;
  }
}
```

In particular this type override tells Luxon that null won't be returned when parsing DateTimes.

Unfortuantely when this is set, it now breaks the AdapaterLuxon type checking when providing it to the LocalizationProvider. This worked without issues on @mui/x-date-pickers-pro version 6.18.4

### Expected behavior

Providing AdapterLuxon to the LocalizationProvider with throwOnInvalid configured to `true` should not cause type errors.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 Browser:
    Chrome, but issue is browser agnostic
 System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: latest => 11.11.3 
    @emotion/styled: latest => 11.11.0 
    @mui/base:  5.0.0-beta.33 
    @mui/core-downloads-tracker:  5.15.6 
    @mui/material: latest => 5.15.6 
    @mui/private-theming:  5.15.6 
    @mui/styled-engine:  5.15.6 
    @mui/system:  5.15.6 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.6 
    @mui/x-date-pickers: latest => 6.19.2 
    @mui/x-date-pickers-pro: latest => 6.19.2 
    @mui/x-license-pro:  6.10.2 
    @types/react: latest => 18.2.48 
    react: latest => 18.2.0 
    react-dom: latest => 18.2.0 
    typescript: latest => 5.3.3 
```
</details>

### Order ID or Support key 💳 (optional)

60670

**Comment by michelengelen** [comment]
Hey @harry-peirse-jfc I can confirm this behavior (bug? 🤷🏼).
I'll put this on the board for the team to evaluate the effort!
Thanks! 🙇🏼

**Comment by andbjer** [comment]
This issue was introduced in v6.18.7. I belive this is the PR that introduced the issue https://github.com/mui/mui-x/pull/11566

**Comment by oscar-b** [comment]
This is easily reproduced by deleting for instance the month part (in the textfield) of a `<DateTimePicker<DateTime>>`

```
Uncaught Error: Invalid DateTime: invalid input
    at DateTime.invalid (datetime.js:940:13)
    at DateTime.fromJSDate (datetime.js:600:23)
    at AdapterLuxon.getInvalidDate (AdapterLuxon.js:208:77)
    at clearActiveSection (useFieldState.js:158:69)
    at eval (useFieldV6TextField.js:283:9)
    at eval (useEventCallback.js:25:19)
    at handleChange (InputBase.js:396:7)
```

```
"@date-io/core": "^3.0.0",
"@date-io/luxon": "^3.0.0",
"@mui/material": "^5.15.16",
"@mui/x-date-pickers": "^7.7.0",
```

**Comment by LukasTy** [comment]
@oscar-b @andbjer @harry-peirse-jfc I've created a [draft PR](https://github.com/mui/mui-x/pull/13486) with an experiment on how to handle this luxon setting.
Consider trying the following package: `https://pkg.csb.dev/mui/mui-x/commit/064c2340/@mui/x-date-pickers` to test the behavior and provide any feedback if possible.
```diff
-"@mui/x-date-pickers": "^7.7.0"
+"@mui/x-date-pickers": "https://pkg.csb.dev/mui/mui-x/commit/064c2340/@mui/x-date-pickers"
```

The main issue/question is how do we handle these "invalid" thrown dates as currently it seems more as a bug than a feature.
Blurring the text field hides the input/query, when the entry is invalid.
Also, IMHO, it would be logical to put the field in an error state when the entry is "invalid/thrown".

https://github.com/mui/mui-x/assets/4941090/5a3812c1-3622-4a23-aad4-2005df123728

What would you consider a proper behavior given the `Settings.throwOnInvalid = true`?
I'll remind you that this setting messes up with the expected [lifecycle behavior](https://mui.com/x/react-date-pickers/lifecycle/) of Fields.
We loose the intermediate `Invalid date` state. 🙈

**Comment by oscar-b** [comment]
@LukasTy Thanks for looking into this. The whole situation with types in Luxon is.. not optimal. I don't know if you did more research, but here's some interesting tickets: 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64995 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65078
https://github.com/moment/luxon/issues/1421

Your PR seems to do the best with the situation at hand (only checked your video, haven't tried it myself yet), but losing the date on blur probably won't fly here. I'll probably have to investigate disabling `throwOnInvalid` in our codebase instead, considering the issues around Luxon wrt this.

**Comment by LukasTy** [comment]
@oscar-b thank you for sharing the discussion links.
I can only add that if luxon went for a separate import path (`luxon/strict`) approach, that could be even harder to support as opposed to the existing solution.

I'm not a fan of this behavior (throwOnInvalid) from the Picker Adapters perspective, because luxon is the only library/adapter, that I'm of, which has such option.
All the other libraries (and even JS `Date`) just create an object, which can be identified as invalid and we rely on this.
Properly supporting `luxon.throwOnInvalid` means creating special checks and cases just to cater to this one implementation case. 🙈 🤷 

Is the lack of support on the `@mui/x-date-pickers` side for `luxon.throwOnInvalid` a deal-breaker for anyone?
Or can we wait and see what direction the library takes?

**Comment by oscar-b** [comment]
@LukasTy For our case, I'm reverting to not using `throwOnInvalid` anymore, so we're good. Hopefully `luxon` will add support for locally specifying `throwOnInvalid` overriding the global setting, but I'm not holding my breath.

**Comment by SaebAmini** [comment]
After a confused long search of why my build was suddenly encountering the below error, I luckily found this thread linked from [the documentation page](https://mui.com/x/react-date-pickers/adapters-locale/) to understand why it's happening.

I'll just paste the error here to help others find this thread from search engines:

`<LocalizationProvider dateAdapter={AdapterLuxon}>` results in the type error:
```
Types of construct signatures are incompatible.
  Type 'new ({ locale, formats }?: { formats?: Partial<AdapterFormats> | undefined; locale?: string | undefined; } | undefined) => AdapterLuxon' is not assignable to type 'new (...args: any) => MuiPickersAdapter<DateTime<true>, string>'.
    Construct signature return types 'AdapterLuxon' and 'MuiPickersAdapter<DateTime<true>, string>' are incompatible.
      The types returned by 'date(...)' are incompatible between these types.
        Type 'DateTime<true> | DateTime<false> | null' is not assignable to type 'DateTime<true> | null'.
          Type 'DateTime<false>' is not assignable to type 'DateTime<true>'.
            Type 'false' is not assignable to type 'true'.ts(2419)
LocalizationProvider.d.ts(22, 5): The expected type comes from property 'dateAdapter' which is declared here on type 'IntrinsicAttributes & LocalizationProviderProps<DateTime<true>, string>'
(property) LocalizationProviderProps<DateTime<true>, string>.dateAdapter?: (new (...args: any) => MuiPickersAdapter<DateTime<true>, string>) | undefined
Date library adapter class function.
```
