### ISSUE TITLE
DataGrid - Cell TextArea resize broken in v7.0.0

### ISSUE THREAD

**Issue by gmconte** [mui/mui-x#12590]
### Search keywords

datagrid textarea resize

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/recipes-editing/#multiline-editing

Steps:
1. Double click on one of the cells of the "Bio" column
2. try to resize vertically by click-and-dragging the resize icon

### Current behavior

The textarea flickers and is difficult to resize it to the desired height.

See video: [Screencast from 2024-03-28 10-16-39.webm](https://github.com/mui/mui-x/assets/3528114/e3fcc799-222c-4b41-bb00-0f4d8a959819)
The same behaviour happens on the latest versions of Chrome, Firefox and Chrome without extensions or plugins

In my dev environment I get the following error repeated many times:
```

Uncaught runtime errors:

ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:73070:58)
    at http://localhost:3000/static/js/bundle.js:73089:7

```

### Expected behavior

The textarea should resize nicely and smoothly

You can see that changing the version of the demo to 6.19.8 resizing works as intended
https://v6.mui.com/x/react-data-grid/recipes-editing/#multiline-editing

### Context

I just updated to version 7.0.0 and noticed the issue.
I then investigated and found the same issue on your demo (https://mui.com/x/react-data-grid/recipes-editing/#multiline-editing) 

### Your environment

This is not related to my code as the issue is noticeable in your demo too

**Comment by michelengelen** [comment]
Thanks @gmconte for raising this issue.
I tried it and can confirm that this is a regression.
I did add this to our board.

**Comment by arminmeh** [comment]
I can't reproduce this on the latest version 7
https://v7.mui.com/x/react-data-grid/recipes-editing/#multiline-editing
It is also not reproducible on the latest version 8
https://mui.com/x/react-data-grid/recipes-editing/#multiline-editing

The issue was fixed as part of some other update.
I will close the issue.
@gmconte if you are still able to reproduce it, please share a new reproduction demo.
