### ISSUE TITLE
[charts] Failed prop type: The prop `bars[0].xOrigin` is marked as required in `BarLabelPlot`

### ISSUE THREAD

**Issue by prolink007** [mui/mui-x#13488]
### Steps to reproduce

Using chrome 125.0.6422.142.

1. Use the [stackblitz](https://stackblitz.com/run?file=Demo.js) from the [BarChart](https://mui.com/x/react-charts/bars/#using-a-dataset) documentation.

2. Add this following code snippet to the `BarChart` component.

```tsx
barLabel={(item, context) => {
  return ""
}}
```

3. Refresh the code and inspect the page. Notice the error in the console.

```
preview-b991ddc586eca.js:2 Warning: Failed prop type: The prop `bars[0].xOrigin` is marked as required in `BarLabelPlot`, but its value is `undefined`.
    at BarLabelPlot (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/BarChart/BarLabel/BarLabelPlot.js:53:7)
    at BarPlot (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/BarChart/BarPlot.js:195:7)
    at g
    at svg
    at eval (https://tsf5u6--run.stackblitz.io/turbo_modules/@emotion/react@11.11.4/dist/emotion-element-f93e57b0.cjs.dev.js:62:23)
    at ChartsSurface (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/ChartsSurface.js:24:7)
    at HighlightedProvider (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/context/HighlightedProvider/HighlightedProvider.js:34:3)
    at InteractionProvider (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/context/InteractionProvider.js:68:5)
    at ZAxisContextProvider (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/context/ZAxisContextProvider.js:25:12)
    at CartesianContextProvider (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/context/CartesianContextProvider.js:35:12)
    at SeriesContextProvider (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/context/SeriesContextProvider.js:66:5)
    at ColorProvider (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/context/ColorProvider.js:18:5)
    at DrawingProvider (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/context/DrawingProvider.js:44:5)
    at ChartContainer (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/ChartContainer/ChartContainer.js:26:5)
    at div
    at eval (https://tsf5u6--run.stackblitz.io/turbo_modules/@emotion/react@11.11.4/dist/emotion-element-f93e57b0.cjs.dev.js:62:23)
    at ResponsiveChartContainer (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/ResponsiveChartContainer/ResponsiveChartContainer.js:21:14)
    at BarChart (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/x-charts@7.7.0/BarChart/BarChart.js:39:5)
    at BarsDataset
    at StyledEngineProvider (https://tsf5u6--run.stackblitz.io/turbo_modules/@mui/styled-engine@5.15.14/node/StyledEngineProvider/StyledEngineProvider.js:27:5)
```

### Current behavior

When adding a `barLabel` to a `BarChart` you get the following error.

```
Warning: Failed prop type: The prop `bars[0].xOrigin` is marked as required in `BarLabelPlot`, but its value is `undefined`.
```

### Expected behavior

I would expect no error.

### Context

Trying to add a `barLabel` to a `BarChart` without an error in the console.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.14.0 - ~\AppData\Local\fnm_multishells\14264_1718114663323\node.EXE
    npm: 10.7.0 - ~\AppData\Local\fnm_multishells\14264_1718114663323\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 125.0.6422.142
    Edge: Chromium (125.0.2535.92)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.19
    @mui/icons-material: ^5.15.18 => 5.15.19
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.18 => 5.15.19
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-charts: ^7.6.2 => 7.6.2
    @mui/x-data-grid: ^7.6.2 => 7.6.2
    @mui/x-date-pickers: ^7.6.2 => 7.6.2
    @types/react:  18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript:  4.9.5

```
</details>

**Search keywords**: barchart

**Comment by michelengelen** [comment]
Hey @prolink007 ... thanks for raising this issue. 🙇🏼 
I can confirm it and will add this to the board!

**Comment by michelengelen** [comment]
For some reason the scale function [here](https://github.com/mui/mui-x/blob/959c9b4ec01b3d1bc6b80c39e2ce05ca4030efee/packages/x-charts/src/BarChart/BarPlot.tsx#L118) will always return `undefined` when called with `0`.

@JCQuintas could you take this?

**Comment by alexfauquette** [comment]
The solution is in the BarPlot component code:

https://github.com/mui/mui-x/blob/master/packages/x-charts/src/BarChart/BarPlot.tsx/#L194-L208


The following code can not work because the x-axis is a band scale by default. So it can only accept values in the `data` property. But the y-axis is a numerical value which can always accept 0
```js
xOrigin: xScale(0)!,
yOrigin: yScale(0)!,
```

We need to adapt the typing
