### ISSUE TITLE
[Data Grid] Header Filters breaks if filterOperators is set to undefined

### ISSUE THREAD

**Issue by sleon-panw** [mui/mui-x#13626]
### Steps to reproduce

Send this prop to the DataGridPremuim component:
```
filterOperators:undefined,
```

### Current behavior

TypeError: Cannot read properties of undefined (reading 'InputComponent')
    at index-Gm61WJDT.js:47281:135
    at renderWithHooks (chunk-4YFJ7OCR.js:18437:26)
    at updateForwardRef (chunk-4YFJ7OCR.js:21214:28)
    at beginWork (chunk-4YFJ7OCR.js:22835:22)
    at HTMLUnknownElement.callCallback2 (chunk-4YFJ7OCR.js:10563:22)
    at Object.invokeGuardedCallbackDev (chunk-4YFJ7OCR.js:10588:24)
    at invokeGuardedCallback (chunk-4YFJ7OCR.js:10622:39)
    at beginWork$1 (chunk-4YFJ7OCR.js:26654:15)
    at performUnitOfWork (chunk-4YFJ7OCR.js:26087:20)
    at workLoopSync (chunk-4YFJ7OCR.js:26026:13)

**Search keywords**: data grid
**Order ID**: I've been emailing support and they gave me this number 19977

**Comment by MBilalShafi** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find examples and guides on how to find templates in our docs with which you can provide examples for your specific use case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
