### ISSUE TITLE
[data grid] Print export does not work in production environments in Chrome

### ISSUE THREAD

**Issue by KseniaKoms** [mui/mui-x#14658]
### The problem in depth

We are encountering an issue with the DataGridPremium component in Chrome where the print window does not appear after clicking the "Print" button in the table toolbar. This issue is observed in production environments but works as expected when deployed on localhost. The print window should be displayed when clicking "Print" in all environments, but currently, it only functions correctly in the localhost environment.

Steps to Reproduce:
1. Set up a DataGridPremium with a toolbar that includes the "Print" option.
2. Open the application in Chrome in a remote environment (e.g., staging or production).
3. Click the "Print" button in the toolbar.
4. Observe that the print window does not appear.

Expected Behavior:
The print window should appear after clicking "Print" in the table toolbar in all environments, including remote ones.

Actual Behavior:
The print window appears only in localhost but does not show up in prod environments.

Environment Details:
Browser: Chrome Version 128.0.6613.138 (Official Build) (arm64)
Localhost: Print window appears
Prod Environments: We are using Vite with esbuild for local setup and opting for Terser in prod setup. Otherwise the environments are identical.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.6.1
  Binaries:
    Node: 21.6.2 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 129.0.6668.59
    Edge: Not Found
    Safari: 17.6
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.36 
    @mui/core-downloads-tracker:  5.15.10 
    @mui/icons-material: ^5.15.0 => 5.15.10 
    @mui/material: ^5.15.0 => 5.15.10 
    @mui/private-theming:  6.0.2 
    @mui/styled-engine:  6.0.2 
    @mui/system: ^6.0.2 => 6.0.2 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.9 
    @mui/x-data-grid:  7.16.0 
    @mui/x-data-grid-premium: ^7.16.0 => 7.16.0 
    @mui/x-data-grid-pro:  7.16.0 
    @mui/x-date-pickers: ^6.18.4 => 6.19.4 
    @mui/x-internals:  7.16.0 
    @mui/x-license:  7.16.0 
    @types/react: 18.2.48 => 18.2.48 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.3 => 5.0.3 
```
</details>

**Search keywords**: DataGrid Chrome Print
**Order ID**: 82865

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by KseniaKoms** [comment]
`import * as React from 'react';
import Box from '@mui/material/Box';
import { useDemoData } from '@mui/x-data-grid-generator';
import { DataGrid } from '@mui/x-data-grid';
import {
  DataGridPremium,
  GridToolbarExport,
  GridToolbarContainer,
  useGridApiRef,
} from '@mui/x-data-grid-premium';

export default function Demo() {
  const { data } = useDemoData({
    dataSet: 'Commodity',
    rowLength: 100000,
    editable: true,
  });
  const apiRef = useGridApiRef();
  return (
    <Box sx={{ width: '100%', height: '100%', position: 'relative' }}>
      <DataGridPremium
        {...data}
        apiRef={apiRef}
        loading={data.rows.length === 0}
        slots={{
          toolbar: () => (
            <GridToolbarContainer
              sx={{
                display: 'flex',
                justifyContent: 'space-between',
                borderBottom: '1px solid #e0e0e0',
                padding: '0.521vw',
                paddingLeft: '0.729vw',
              }}
            >
              <GridToolbarExport
                printOptions={{ hideFooter: true, hideToolbar: true }}
              />
            </GridToolbarContainer>
          ),
        }}
        rowHeight={38}
        checkboxSelection
      />
    </Box>
  );
}

**Comment by KseniaKoms** [comment]
`import * as React from 'react';
import Box from '@mui/material/Box';
import { useDemoData } from '@mui/x-data-grid-generator';
import { DataGrid } from '@mui/x-data-grid';
import {
  DataGridPremium,
  GridToolbarExport,
  GridToolbarContainer,
  useGridApiRef,
} from '@mui/x-data-grid-premium';

export default function Demo() {
  const { data } = useDemoData({
    dataSet: 'Commodity',
    rowLength: 100000,
    editable: true,
  });
  const apiRef = useGridApiRef();
  return (
    <Box sx={{ width: '100%', height: '100%', position: 'relative' }}>
      <DataGridPremium
        {...data}
        apiRef={apiRef}
        loading={data.rows.length === 0}
        slots={{
          toolbar: () => (
            <GridToolbarContainer
              sx={{
                display: 'flex',
                justifyContent: 'space-between',
                borderBottom: '1px solid #e0e0e0',
                padding: '0.521vw',
                paddingLeft: '0.729vw',
              }}
            >
              <GridToolbarExport
                printOptions={{ hideFooter: true, hideToolbar: true }}
              />
            </GridToolbarContainer>
          ),
        }}
        rowHeight={38}
        checkboxSelection
      />
    </Box>
  );
}
`

**Comment by michelengelen** [comment]
which framework are you using? Next? This might prove important to find the cause

**Comment by KseniaKoms** [comment]
No, I use React.

**Comment by arminmeh** [comment]
@KseniaKoms 
can you please share relevant config files, so that we can match the setup that you have?

**Comment by KseniaKoms** [comment]
Which config files do you mean? If config for DataGrid table component I provided it in previous comment and the rest part of handlers I cannot share. Or do you mean packages config?

**Comment by arminmeh** [comment]
>Or do you mean packages config?
yes
config used to build and prod environment details (os, node version, etc.)
so that I can try to reproduce the setup and the error

**Comment by arminmeh** [comment]
>Prod Environments: We are using Vite with esbuild for local setup and opting for Terser in prod setup. Otherwise the environments are identical.

Did you try to run prod setup locally?

Can you share the scripts you use to build and run the app (both local and prod)?

**Comment by arminmeh** [comment]
@KseniaKoms 
which tool are you using to build and serve the app?
Can you share if you have any cli arguments passed to those commands?

**Comment by KseniaKoms** [comment]
We use vite

` "build": "vite build --minify false",
    "serve": "vite preview --port 3000",`

**Comment by KseniaKoms** [comment]
That was the first that we did. But print works as expected even I serve prod build local.

**Comment by arminmeh** [comment]
@KseniaKoms did you try deploying stripped down version of the app on the prod environment to check if some other features interfere with the print
You can use first [Export demo](https://mui.com/x/react-data-grid/export/#default-toolbar) to test it out

**Comment by KseniaKoms** [comment]
It not helped, we have tried. But all our build setup works as expected in Safari.

**Comment by arminmeh** [comment]
Did you try with Chrome in incognito mode (to run it without extensions?)

To recap:
Your app or the demo app deployed on production does not show print window in any other browser but Safari
Locally, everything is working fine (even in production mode)

Is that correct?

**Comment by KseniaKoms** [comment]
Correct. In Chrome in incognito mode locally it works also fine.

**Comment by arminmeh** [comment]
@mui/xgrid anyone has any other suggestion?

**Comment by thomasdiesenreiter** [comment]
we have the same issue here. printing works in safari and firefox, but not in chrome.

**Comment by arminmeh** [comment]
@thomasdiesenreiter do you have any errors that would help pinpoint the cause?

**Comment by thomasdiesenreiter** [comment]
@arminmeh I have to get back to my devs

**Comment by michelengelen** [comment]
@arminmeh I just randomly ran across this issue (or a similar one) myself.
I could print in Firefox, but not in Chrome.
Chrome however prints a warning:
<details>
  <summary>Warning from print export</summary>
```
GridPagination.tsx:136 MUI X: The page size `4` is not present in the `pageSizeOptions`.
Add it to show the pagination select. 
    at GridPagination (webpack-internal:///../packages/x-data-grid/src/components/GridPagination.tsx:76:99)
    at div
    at eval (webpack-internal:///../node_modules/.pnpm/@emotion+react@11.13.3_@types+rea…otion/react/dist/emotion-element-7a1343fa.browser.development.esm.js:70:66)
    at GridFooterContainer (webpack-internal:///../packages/x-data-grid/src/components/containers/GridFooterContainer.tsx:53:7)
    at GridFooter (webpack-internal:///../packages/x-data-grid/src/components/GridFooter.tsx:35:99)
    at GridFooterPlaceholder (webpack-internal:///../packages/x-data-grid/src/components/base/GridFooterPlaceholder.tsx:18:100)
    at div
    at eval (webpack-internal:///../node_modules/.pnpm/@emotion+react@11.13.3_@types+rea…otion/react/dist/emotion-element-7a1343fa.browser.development.esm.js:70:66)
    at GridRoot (webpack-internal:///../packages/x-data-grid/src/components/containers/GridRoot.tsx:48:100)
    at GridContextProvider (webpack-internal:///../packages/x-data-grid/src/context/GridContextProvider.tsx:22:3)
    at DataGrid (webpack-internal:///../packages/x-data-grid/src/DataGrid/DataGrid.tsx:46:84)
    at div
    at ExportDefaultToolbar (webpack-internal:///./pages/playground/demo.tsx:22:78)
    at Ye (webpack-internal:///../node_modules/.pnpm/styled-components@6.1.13_react-do…e_modules/styled-components/dist/styled-components.browser.esm.js:30:16099)
    at StyledEngineProvider (webpack-internal:///../node_modules/.pnpm/@mui+monorepo@https+++codeload.gi…_modules/@mui/monorepo/docs/src/modules/utils/StyledEngineProvider.js:40:5)
    at CodeVariantProvider (webpack-internal:///../node_modules/.pnpm/@mui+monorepo@https+++codeload.gi…t7sa/node_modules/@mui/monorepo/docs/src/modules/utils/codeVariant.js:55:5)
    at CodeStylingProvider (webpack-internal:///../node_modules/.pnpm/@mui+monorepo@https+++codeload.gi…e_modules/@mui/monorepo/docs/src/modules/utils/codeStylingSolution.js:55:5)
    at CodeCopyProvider (webpack-internal:///../node_modules/.pnpm/@mui+monorepo@https+++codeload.gi…de_modules/@mui/monorepo/packages/mui-docs/src/CodeCopy/CodeCopy.tsx:181:3)
    at TranslationsProvider (webpack-internal:///../node_modules/.pnpm/@mui+monorepo@https+++codeload.gi…skt7sa/node_modules/@mui/monorepo/packages/mui-docs/src/i18n/i18n.tsx:35:3)
    at UserLanguageProvider (webpack-internal:///../node_modules/.pnpm/@mui+monorepo@https+++codeload.gi…skt7sa/node_modules/@mui/monorepo/packages/mui-docs/src/i18n/i18n.tsx:76:5)
    at AdProvider (webpack-internal:///../node_modules/.pnpm/@mui+monorepo@https+++codeload.gi…sa/node_modules/@mui/monorepo/packages/mui-docs/src/Ad/AdProvider.tsx:22:5)
    at DocsProvider (webpack-internal:///../node_modules/.pnpm/@mui+monorepo@https+++codeload.gi…les/@mui/monorepo/packages/mui-docs/src/DocsProvider/DocsProvider.tsx:21:3)
    at AppWrapper (webpack-internal:///./pages/_app.js:185:5)
    at MyApp (webpack-internal:///./pages/_app.js:419:5)
    at PathnameContextProviderAdapter (webpack-internal:///../node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_@…nsdmgq3gkuvevjge/node_modules/next/dist/shared/lib/router/adapters.js:89:7)
    at ErrorBoundary (webpack-internal:///../node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_@…/next/dist/client/components/react-dev-overlay/pages/ErrorBoundary.js:43:5)
    at ReactDevOverlay (webpack-internal:///../node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_@…ext/dist/client/components/react-dev-overlay/pages/ReactDevOverlay.js:34:5)
    at Container (webpack-internal:///../node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_@…gin_muvr5ye73wnsdmgq3gkuvevjge/node_modules/next/dist/client/index.js:80:1)
    at AppContainer (webpack-internal:///../node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_@…in_muvr5ye73wnsdmgq3gkuvevjge/node_modules/next/dist/client/index.js:191:5)
    at Root (webpack-internal:///../node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_@…in_muvr5ye73wnsdmgq3gkuvevjge/node_modules/next/dist/client/index.js:423:5)
```
</details>

I did use the normal playground in dev environment. 
Not sure why this happens though. 🤷🏼 

The relevant piece of code is here: https://github.com/mui/mui-x/blob/4bc5acc101590bf64eef33270ef803647e249dde/packages/x-data-grid/src/components/GridPagination.tsx#L131-L145

This is also very likely a problem with Chrome and not our component as the last change made to this is 6 months old.

I'll also include a screen recording of it.

https://github.com/user-attachments/assets/32fed52b-c8b2-437d-841c-5f93b4ff1e2b

Hope this helps!

**Comment by arminmeh** [comment]
thanks @michelengelen, I will take a look

**Comment by arminmeh** [comment]
this `console.warn` should not be there at all in prod, since it is wrapped in that condition
Additionally, this only complains about the prop misalignment. Not sure if that would cause any problems.

Can you open console in Firefox and see if you get that warning and still have the print window open?

Also, can you share the demo code you used for the video?
It would be great if I can reproduce the issue on my side.

**Comment by michelengelen** [comment]
Demo code is from this section: [Default Toolbar](https://mui.com/x/react-data-grid/export/#default-toolbar)

The warning also fires in Firefox, so probably not related. 
This really gives the impression that there is something we are missing on Chrome side, rather our code ... did they change something recently on the print feature/window?

**Comment by michelengelen** [comment]
One thing I just noticed (might be related) is that the iframe appears and disappears in an instant in Chrome. Hardly noticable in the video, so i took a screenshot:
<img width="2346" alt="Screenshot 2024-10-11 at 08 59 49" src="https://github.com/user-attachments/assets/75aab5f4-bb22-4cc1-af88-5b7bbb653924">

**Comment by michelengelen** [comment]
In Firefox you can see that this is attached to an event called `handlePrintWindowOpen`
<img width="623" alt="Screenshot 2024-10-11 at 09 05 34" src="https://github.com/user-attachments/assets/a62a5cae-0603-4b7d-8c8f-a2ff85fdc8d1">

**Comment by michelengelen** [comment]
`handlePrintWindowLoad` runs as expected, but then the print gets cancelled for some reason and immediately jumps into the cleanup: `handlePrintWindowAfterPrint` which removes the iframe again!

**Comment by arminmeh** [comment]
For me it works fine, so maybe it is related to some chrome/system setting?
I am using Chrome 129.0.6668.101

**Comment by michelengelen** [comment]
I am on a similar version: 129.0.6668.91
I'll try updating and check if thats the problem!

**Comment by arminmeh** [comment]
Can you check the differences in Firefox and Chrome at this point
https://github.com/mui/mui-x/blob/v7.19.0/packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx#L369

**Comment by michelengelen** [comment]
Ok, updating to your version helped ... This might be a chrome related bug after all!

**Comment by michelengelen** [comment]
> Can you check the differences in Firefox and Chrome at this point https://github.com/mui/mui-x/blob/v7.19.0/packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx#L369

There are no differences ... for some reason Chrome closed the print window and FF kept it open!

**Comment by arminmeh** [comment]
@KseniaKoms @thomasdiesenreiter 
can you check if updating Chrome resolves the issue?

**Comment by KseniaKoms** [comment]
I`ve just updated Chrome after your comment, but it didn`t help.

**Comment by arminmeh** [comment]
the problem is that @michelengelen can't reproduce the issue anymore
anyone else from @mui/xgrid can reproduce it?

I am interested if this is the line where it gets wrong
https://github.com/mui/mui-x/blob/v7.19.0/packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx#L139

**Comment by michelengelen** [comment]
I still have the logs from FF:
<img width="1271" alt="Screenshot 2024-10-11 at 12 00 36" src="https://github.com/user-attachments/assets/c9594143-a028-49cf-a713-1eefdd9d575b">

The only difference with Chrome was, that the 'change' event got fired 3 times. And the value in `mql.matches` was `true`, `false`, `true` during the 3 calls.

With the updated chrome this fires correctly:
- once for showing the print dialog
- a second time after printing or cancelling

Firefox runs the callback twice as well, without action taken from the user:
https://github.com/user-attachments/assets/b3b52aca-75f1-4b67-911a-b2685808baa6

The bug now appears again for me as well ... although on the new Chrome version. I logged the `mql` object here as well and noticed that `mql.matches` is always `false`, only sometimes it will run as `true` and thats when the print dialog appears:
<img width="1269" alt="Screenshot 2024-10-11 at 12 16 04" src="https://github.com/user-attachments/assets/f1755750-9ba9-4cac-aded-6fbc6b0dc907">

This is super weird and not easily reproducible as it sometimes shows on first try, but most of the time it takes like 20-30 clicks

**Comment by KseniaKoms** [comment]
We also tested on the latest versions our packages but still don't see print window. We used 
`{
  "dependencies": {
    "@emotion/cache": "^11.13.1",
    "@emotion/react": "11.11.4",
    "@emotion/styled": "^11.13.0",
    "@mui/material": "^6.1.4",
    "@mui/system": "^6.1.4",
    "@mui/x-data-grid-premium": "^7.21.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "terser": "^5.36.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "@vitejs/plugin-react": "^2.0.0",
    "typescript": "^4.6.4",
    "vite": "4.2.3"
  }
}`

**Comment by cherniavskii** [comment]
Can't reproduce it in Chrome on Windows 11:

https://github.com/user-attachments/assets/511687ee-5e64-4c76-8ce5-14e76df78ec3

@KseniaKoms Can you reproduce the issue here https://mui.com/x/react-data-grid/export/#default-toolbar?
Also, what is the size of your dataset?

**Comment by KseniaKoms** [comment]
@cherniavskii I can not reproduce this issue, only in our production environment. We have dynamic dataset, it could be 5 records or 15000 records.

**Comment by mtr1990** [comment]
Having same problem with Chrome.

Tested on:
- Safari
- Firefox
- Chrome => Sometimes works on Production, sometimes doesn't (Dev mode is always not work)
 
 


https://github.com/user-attachments/assets/95b5f6cf-d924-47be-af7b-aaf7481c9ec9

**Comment by arminmeh** [comment]
@mtr1990 
for you the dev mode is always failing?
can you share the your environment details?

**Comment by mtr1990** [comment]
The problem appears on the Vite.js version

Next.js still works normally. Sometimes it doesn't work (very rarely).

In addition, Safari and Firefox still work normally. I tested it in an anonymous browser so there will be no conflicts with extensions

```tsx
node v20.18.1
chrome version 130.0.6723.119 (Official Build) (arm64)
```

Vite.js version
```tsx
"vite": "^5.4.11",
"@mui/x-data-grid": "^7.22.2",
```

Next.js version
```tsx
"next": "^14.2.18",
"@mui/x-data-grid": "^7.22.2",
```

https://github.com/user-attachments/assets/fccc2c10-5eb3-48a1-9e0a-b4d36072a53e

**Comment by mtr1990** [comment]
Update!

Just updated `Chrome Version 131.0.6778.86 (Official Build) (arm64)`

And it works again with Vite.js version.

But I think this is still a potential problem that needs attention.

Because it's the same code, same browser version. Next.js works and Vite.js doesn't

https://github.com/user-attachments/assets/d73478e6-43d7-4914-bcf8-0665a2ba989e

**Comment by Shemrock3267** [comment]
I also want to add this point about styles.
**Version**: "@mui/x-data-grid": "^7.25.0"

**Error** occurs in production when clicking print: 
```
TypeError: Cannot read properties of null (reading 'style')
  at handlePrintWindowLoad (../../node_modules/@mui/x-data-grid/hooks/features/export/useGridPrintExport.js:128:25)
  at printWindow.onload (../../node_modules/@mui/x-data-grid/hooks/features/export/useGridPrintExport.js:258:9)
```

**Comment by borntorun** [comment]
Hi,

I also was having this problem in development, the print dialog not opening in chrome.

I think the issue is this [line/block](https://github.com/mui/mui-x/blob/52601483fbc978b1f3d0f99562b20d807889e06b/packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx#L267) 
and related somehow with the stylesheets loading (time delays, sync...) . 

I discover when googling about print problems with iframes and discover this [issue](https://stackoverflow.com/questions/47960802/iframe-print-not-working-in-chrome-when-url-starts-with-https) on stackoverflow that points me to a possible solution.

I just changed the block to this adding a timeout for open the print dalog:

```
// Trigger print
    if (process.env.NODE_ENV !== 'test') {
      // wait for remote stylesheets to load
      Promise.all(stylesheetLoadPromises).then(() => {
        setTimeout(function () {
          printWindow.contentWindow.print();     
        }, 1000);
        // printWindow.contentWindow.print();
      });
    }
```

And not it works on my local environment.

(the [style](https://github.com/mui/mui-x/issues/14658#issuecomment-2657120190) error related to hiding footer still occurs)
