### ISSUE TITLE
DatePicker Error - Cannot read properties of null (reading 'selectionStart')

### ISSUE THREAD

**Issue by brandong954** [mui/mui-x#14684]
### Search keywords

DatePicker selectionStart 

### Latest version

- [X] I have tested the latest version

### Affected products

Date and Time Pickers

### Steps to reproduce

Steps:
1. Add any `htmlInput` override for `MuiTextField` `slotProps` within createTheme()`:

```
let theme = createTheme({
  components: {
    MuiTextField: {
      defaultProps: {
        slotProps: {
          htmlInput: {
            sx: {
              margin: "10px 0",
            },
          }
        },
      },
    },
  },
});
```
2. Add a `DatePicker` component to the application.
3. Click on the input text field of the date picker.

### Current behavior

The following runtime error is presented when replicating on desktop (haven't tried mobile):

```
Uncaught TypeError: Cannot read properties of null (reading 'selectionStart')
    at syncSelectionFromDOM (useFieldV6TextField.js:142:1)
    at useFieldV6TextField.js:185:1
    at useEventCallback.js:18:1
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Sl.dtAWF [as aWF] (745a23c5b80d9e64_complete.js:265:226)
    at Qb.dispatchWrapper (745a23c5b80d9e64_complete.js:424:156)
    at z.dispatchEvent (745a23c5b80d9e64_complete.js:410:187)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
```

### Expected behavior

Able to click on the date picker input without the application crashing.

### Context

Should be able to override the `htmlInput` slot prop for `TextField` at the theme level without negatively affecting `DatePicker` input.

Luckily, I was able to replace my `htmlInput` slotProp with the `input` `slotProp` to get things working.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browsers:
    Microsoft Edge
      Version 129.0.2792.52 (Official build) (arm64)
    Google Chrome
      Version 128.0.6613.139 (Official Build) (arm64)
  System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 22.9.0 - /usr/local/bin/node
    npm: 10.8.3 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.3
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/core-downloads-tracker:  6.1.0
    @mui/icons-material: ^6.1.0 => 6.1.0
    @mui/material: ^6.1.0 => 6.1.0
    @mui/private-theming:  6.1.0
    @mui/styled-engine:  6.1.0
    @mui/system:  6.1.0
    @mui/types:  7.2.16
    @mui/utils:  6.1.0
    @mui/x-date-pickers: ^7.17.0 => 7.17.0
    @mui/x-internals:  7.17.0
    @types/react:  18.3.7
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
```
</details>

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by brandong954** [comment]
Sorry, I've provided everything I can for now.

**Comment by michelengelen** [comment]
Without a reproduction its hard for us to tell you whats wrong with your implementation.
From the provided code I can already tell you that `slotProps` is not a valid property for `MuiTextField.defaultProps`.
Considering this we are not able to pinpoint the problem, as even with a custom theme it works just fine for me.

**Comment by brandong954** [comment]
Weird, not sure how my theme overrides are working then, but shouldn't `slotProps` be a valid option for `MuiTextField.defaultProps` since `slotProps` is a prop for [`TextField`](https://mui.com/material-ui/api/text-field/#:~:text=of%20the%20component.-,slotProps,-%7B%20formHelperText%3F%3A%20func%0A%7C%C2%A0object)?

(Side note, the MUI 5 -> 6 migration tools actually [reconfigured](https://mui.com/x/migration/migration-pickers-v5/#component-slots-component-slot-props) my theme with the `slotProps` property for `MuiTextField.defaultProps`).

**Comment by michelengelen** [comment]
It is ... but I tested this on the current release ... which version are you using atm?

**Comment by brandong954** [comment]
Similar issue also occurring with [`Autocomplete`](https://github.com/mui/mui-x/issues/14684).

**Comment by sai6855** [comment]
@brandong954 can you set @mui/material version as `"https://pkg.csb.dev/mui/material-ui/commit/aeadff06/@mui/material"` and try again? looks like this issue should be solved by https://github.com/mui/material-ui/pull/43606

**Comment by brandong954** [comment]
Sorry, I'm a noob still with `package.json` nuances, but how can I tell it to use `https://pkg.csb.dev/mui/material-ui/commit/aeadff06/@mui/material` for `@mui/material`?

However, after switching `defaultProps` to `styleOverrides` within my theme, everything is working as intended. Seems like both should be valid approaches though, and perhaps the latest updates make it possible.

**Comment by michelengelen** [comment]
Looks like the linked PR fixes that issue, so I did link it to this as well.
Could you update to the new version once this gets released and report back? 

---

As for the installation of specific commits or from a different source. You can find that information in the [npm docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#git-urls-as-dependencies), but for this specific case it would require you to run:

```bash
npm i https://pkg.csb.dev/mui/material-ui/commit/aeadff06/@mui/material
```
... the result is that the package manager resolves `@mui/material` to the provided URL:

```json
    ...
    "@mui/material": "https://pkg.csb.dev/mui/material-ui/commit/aeadff06/@mui/material",
    ...
```

**Comment by DiegoAndai** [comment]
I'm not very familiar with the DatePicker's code, but what I think it's happening:

- `DatePicker` somewhere relies on setting the `TextField`'s `inputProps`/`slotProps.htmlInput` prop
- By setting the default prop of the `TextField`'s `slotProps.htmlInput` value, the above is overridden, breaking the `DatePicker`.

Makes me think we're missing the infrastructure to merge the `slotProps` from `defaultProps` correctly, this will also happen in the `Autocomplete` component, for example. It's related but **not exactly the same** as https://github.com/mui/material-ui/issues/43573.

This can indeed be fixed by https://github.com/mui/material-ui/pull/43606, but I don't think it's the best solution, because:

- It only solves it in the `Textfield` component, but this is an architecture issue that we might face with all components
- The root cause for the issues is not exactly the same.

Could we have someone from the @mui/x team debug this and confirm my theory? We can work on a proper solution if this is confirmed.

**Comment by GuysmoB** [comment]
Same problem for me when i tried to add my custom Textfield in the TimeField component

```
<TimeField
value={moment(slot.startTime, 'HH:mm')}
onChange={handleTimeChange(day, i, 'startTime')}
format='HH:mm'
ampm={false}
slots={{
 textField: (params) => ( <CRSTextField {...params} sx={{ width: rem(80), height: rem(40) }}	/>	)
}}
/> 
```

This happen because I added some style in the inputProps field from CRSTextField. If i comment it, problem doesnt appear.

**Comment by HerrZatacke** [comment]
As this issue is persisting for a while now, I thought I'd share my (I admit, hacky) solution:

for me this error is caused by setting `MuiTextField.defaultProps.slotProps.htmlInput` to generally disable autocomplete etc. globally for all my `<TextField>` instances.

I decided to wrap my `<DateTimePicker>` with a separate theme which I derive from the existing theme.
This allows me to "remove" the slotProps for the htmlInput while still being able to use all the rest of my actual theme.

I don't know if this has any huge performance implications, but in my case the `<DateTimePicker>` is not actually rendered very often, so at least for me it's a feasible solution which is also easily removed/reverted in case this gets fixed.

```tsx
function MyComp = () => {
  const theme = useTheme();
  const pickerTheme = useMemo<Theme>((): Theme => {
    if (!theme.components?.MuiTextField) {
      return theme;
    }

    const textFieldTheme= {
      ...theme.components.MuiTextField,
    };

    if (textFieldTheme.defaultProps?.slotProps?.htmlInput) {
      delete textFieldTheme.defaultProps.slotProps.htmlInput;
    }

    return ({
      ...theme,
      components: {
        ...theme.components,
        MuiTextField: textFieldTheme,
      },
    });
  }, [theme]);

  return (
    <ThemeProvider theme={pickerTheme}>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <DateTimePicker
          label="Date / Time"
          value={dayjs()}
          onAccept={() => { /* */ }}
        />
      </LocalizationProvider>
    </ThemeProvider>
  );  
}
```

**Comment by LukasTy** [comment]
> Could we have someone from the [@mui/x](https://github.com/orgs/mui/teams/x) team debug this and confirm my theory? We can work on a proper solution if this is confirmed.

@DiegoAndai, I can confirm that the root of the problem is as you expected. If `slotProps` are provided, `inputProps` are overridden.
We pass `inputMode` via `inputProps` to the `TextField` component in case of components with `enableAccessibleFieldDOMStructure={false}` (on v8).

Below is a diff fixing the problem on Picker's side.
It would still have false positives and race conditions (i.e., merging `sx` from different sources) as is, but that would alleviate at least 95% of issues. 🤔 
Could the merging be done on Material side? 🤔 

```diff
diff --git a/packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx b/packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx
index 5099623dce..327f1637ba 100644
--- a/packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx
+++ b/packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx
@@ -7,6 +7,7 @@ import MuiTextField, { TextFieldProps } from '@mui/material/TextField';
 import MuiIconButton, { IconButtonProps } from '@mui/material/IconButton';
 import MuiInputAdornment, { InputAdornmentProps } from '@mui/material/InputAdornment';
 import { SvgIconProps } from '@mui/material/SvgIcon';
+import { major as materialMajor } from '@mui/material/version';
 import useSlotProps from '@mui/utils/useSlotProps';
 import { MakeOptional, SlotComponentPropsFromProps } from '@mui/x-internals/types';
 import { FieldOwnerState } from '../../models';
@@ -78,8 +79,29 @@ export const cleanFieldResponse = <
     openPickerAriaLabel,
     textFieldProps: {
       ...other,
-      InputProps: { ...(InputProps ?? {}), readOnly },
-      inputProps: { ...(inputProps ?? {}), inputMode, onPaste, onKeyDown, ref: inputRef },
+      ...(materialMajor >= 6
+        ? {
+            slotProps: {
+              ...other?.slotProps,
+              input: {
+                ...other?.slotProps?.input,
+                ...(InputProps ?? {}),
+                readOnly,
+              },
+              htmlInput: {
+                ...other?.slotProps?.htmlInput,
+                ...(inputProps ?? {}),
+                inputMode,
+                onPaste,
+                onKeyDown,
+                ref: inputRef,
+              },
+            },
+          }
+        : {
+            InputProps: { ...(InputProps ?? {}), readOnly },
+            inputProps: { ...(inputProps ?? {}), inputMode, onPaste, onKeyDown, ref: inputRef },
+          }),
     },
   };
 };
```

**Comment by DiegoAndai** [comment]
@LukasTy we already handle this on the Material UI side for slotProps: https://github.com/mui/material-ui/blob/master/packages/mui-utils/src/resolveProps/resolveProps.ts#L33

This is why the diff you shared fixes the issue.

I'm not sure backporting this infrastructure to `inputProps`/`InputProps` would be the right path. Given Material UI v5 to v6 should be a straightforward update, I would rather start by nudging users to migrate.

**Comment by LukasTy** [comment]
Thanks for the input @DiegoAndai, however, this still leaves Pickers with an erroneous state given a specific use of props that we need to handle. 🤔 
IMHO, the provided solution should cover the majority of use cases, WDYT?

**Comment by DiegoAndai** [comment]
@LukasTy I'm still unsure. If we do this with these two props, should we do it with all similar deprecated props? Should we do it in all versions, or only v5? I understand that this causes an error, but it doesn't seem that common given the upvotes on the issue. This, of course, doesn't mean that it isn't important, but I would at least attempt guiding the impacted users to migrate before opening this can of worms of adding new functionality to deprecated props. At some point, we need to move on. Material UI v6 is now almost a year old.

**Comment by LukasTy** [comment]
> I'm still unsure. If we do this with these two props, should we do it with all similar deprecated props?

@DiegoAndai I'm only referring to these props, since they trigger a critical component failure if the new API is used.
I would say that it's acceptable to have the remedy in the Pickers package, due to the product decision of supporting the v5 of `@mui/material` along the newer versions in the latest major of `@mui/x-date-pickers`.

> At some point, we need to move on. Material UI v6 is now almost a year old.

I would have loved us to drop support for v5 in the v8 of X packages, but the final decision was to ease the adoption/migration path for users and keep the legacy support.
Now we are bearing the consequences of this choice. 🙈

**Comment by DiegoAndai** [comment]
> I would say that it's acceptable to have the remedy in the Pickers package

Let's see how it goes. If many users complain, we can rediscuss patching in on Material UI 👌🏼

**Comment by heath-freenome** [comment]
@LukasTy @DiegoAndai I just started getting this today in my unit tests when upgrading `@mui/x-date-pickers` to `8.11.2`

It looks like `8.11.2` changed how `slotProps` work and now it broke my code. Can you rollback the fix or update it so that the problem goes away.

We are passing `DatePicker` the following `slotProps`:
```
slotProps={{
    "textField": {
        "ref": null,
        "slotProps": {
            "input": {
                "aria-describedby": "testid__error testid__description testid__help"
            },
            "htmlInput": {
                "type": "text"
            },
            "formHelperText": {
                "id": "testid__help"
            }
        },
        "data-testid": "2456e449-88a3-426f-9df9-e15d4318b864",
        "id": "testid",
        "label": "",
        "placeholder": "",
        "autoFocus": false,
        "error": false,
        "readonlyEmptyValue": "",
        "labelNote": <react node>,
        "disabled": false,
        "className": "TextInput-InputAdornmentCenter"
    },
    "openPickerIcon": {
        "color": "info"
    },
    "openPickerButton": {
        "disableRipple": true
    }
}}
```

**Comment by heath-freenome** [comment]
@LukasTy should I create a new issue or will you reopen this one?

**Comment by LukasTy** [comment]
@heath-freenome Could you provide a reproduction example in the form of a CodeSandbox or StackBlitz demo?
It's slightly unclear to me what the actual use case is.
I would appreciate it if you would pinpoint the concrete issue.

P.S. I've tested `DatePicker` with both variants of `enableAccessibleFieldDOMStructure` property and most if not all of your properties seem to be applied. 🤷

**Comment by heath-freenome** [comment]
Well, the `textField` in question is a wrapper around the `TextField` component, so maybe that is the problem? I'll work on coming up with a test case as soon as I can. My original question stands around reopening vs creating a new one?

**Comment by LukasTy** [comment]
> Well, the `textField` in question is a wrapper around the `TextField` component, so maybe that is the problem?

It could be. Depends how your wrapper handles props and what value is set for `enableAccessibleFieldDOMStructure` prop.

> My original question stands around reopening vs creating a new one?

I would say it depends on the root cause of the issue.
Is it still basically the same problem? Then consider reopening (or asking for it to be reopened).
If it's a different problem to what the original issue was about - a new issue might be a better fit. 🤔

**Comment by heath-freenome** [comment]
@LukasTy Here is a reproducible [test case](https://codesandbox.io/p/sandbox/s273t6) in CodeSandbox, just click on the field. Please let me know whether this is the same issue or a new one I need to write. Or perhaps, some quick way to fix the `TextField`

**Comment by LukasTy** [comment]
@heath-freenome The issue is here:
```ts
const UpdatedHtmlInputProps: InputBaseProps["inputProps"] = {
   ...htmlInput,
   ...otherHtmlInputProps,
};
```
If instead you replace `htmlInput: UpdatedHtmlInputProps` with only `htmlInput`, your example works.
Merging slot props in this way is dangerous and can often not work, since it will not support the callback version of slotProps.

I would suggest you have a second look at your `TextInput` component and assert what is actually needed there. 🤔 
As a lot of the logic seems like it could be removed and the component should work as before with maybe very minor tweaks on how you provide props.

**Comment by heath-freenome** [comment]
> [@heath-freenome](https://github.com/heath-freenome) The issue is here:
> 
> const UpdatedHtmlInputProps: InputBaseProps["inputProps"] = {
>    ...htmlInput,
>    ...otherHtmlInputProps,
> };
> If instead you replace `htmlInput: UpdatedHtmlInputProps` with only `htmlInput`, your example works. Merging slot props in this way is dangerous and can often not work, since it will not support the callback version of slotProps.
> 
> I would suggest you have a second look at your `TextInput` component and assert what is actually needed there. 🤔 As a lot of the logic seems like it could be removed and the component should work as before with maybe very minor tweaks on how you provide props.

@LukasTy What I gave you in my example is a paired down example of `TextInput`... It's does a lot more, so some of the logic you see is needed for other reasons.

Where I'm confused is that `htmlInput` in my example is `undefined`, while `otherHtmlInputProps` actually contains the following as provided by the `DateField` component. It seems like one (or more) of the callbacks in the props are what causes the issue.

<img width="259" height="85" alt="Image" src="https://github.com/user-attachments/assets/98539259-e83f-4236-842e-df8121251598" />

So do I need to write up a new issue?

**Comment by LukasTy** [comment]
Hey @heath-freenome, I've found the issue that was introduced by the previous PR.
Created a fix for it: https://github.com/mui/mui-x/pull/19713.
You can test if it solves your issue by installing the package from: `https://pkg.pr.new/mui/mui-x/@mui/x-date-pickers@5f6f0ed`.

**Comment by heath-freenome** [comment]
@LukasTy Yes, it does seem to fix the issue! Looking forward to picking up this fix from a released version
