### ISSUE TITLE
undefined.id error in 7.22.0 datagrid premium

### ISSUE THREAD

**Issue by frattaro** [mui/mui-x#15170]
### Steps to reproduce

My dependabot PR for the latest (7.21.0 -> 7.22.0) datagrid-premium is running (playwright) tests and I'm getting this

```
MUI: The `anchorEl` prop provided to the component is invalid.
The anchor element should be part of the document layout.
Make sure the element is present in the document or that it's not display none.
Uncaught exception: "TypeError: Cannot read properties of undefined (reading 'id')"
The above error occurred in the <ForwardRef(DataGridPremium)> component:

    at DataGridPremium (webpack-internal:///./node_modules/@mui/x-data-grid-premium/esm/DataGridPremium/DataGridPremium.js:46:101)
```

For reference, this is the error in prod mode (pretty useless):
```
TypeError: Cannot read properties of undefined (reading 'id')
    at Object.current (http://localhost:3000/_next/static/chunks/585-57d76c169312c14d.js:36:51628)
    at ic.<anonymous> (http://localhost:3000/_next/static/chunks/585-57d76c169312c14d.js:23:17305)
    at ic.emit (http://localhost:3000/_next/static/chunks/585-57d76c169312c14d.js:32:50528)
    at Object.publishEvent (http://localhost:3000/_next/static/chunks/585-57d76c169312c14d.js:32:55564)
```

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid

**Comment by frattaro** [comment]
could `nextRow` be undefined?
![image](https://github.com/user-attachments/assets/87bdffe7-1913-4cbf-87bb-5c15c66d7a71)

**Comment by arminmeh** [comment]
Hi @frattaro 
This issue is fixed in https://github.com/mui/mui-x/pull/15153
The fix will be released this week
