### ISSUE TITLE
[charts] "Warning: Encountered two children with the same key, `horizontal-`" when setting yAxis scaleType to "log"

### ISSUE THREAD

**Issue by dandrei** [mui/mui-x#15303]
### Steps to reproduce

Link to live example: [(required)](https://codesandbox.io/p/sandbox/jolly-payne-s69npm)

Steps:
1. Go to the live example showing a very simple line chart with a logarithmic scale, and check the console.

### Current behavior

The following warning is displayed:

```
Warning: Encountered two children with the same key, `horizontal-`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted â€” the behavior is unsupported and could change in a future version.
    at ChartsGridHorizontal (node_modules/@mui/x-charts/ChartsGrid/ChartsHorizontalGrid.js:13:16)
    at g
    at eval (node_modules/@emotion/react/dist/emotion-element-832b737b.browser.cjs.js:71:23)
    at ChartsGrid (node_modules/@mui/x-charts/ChartsGrid/ChartsGrid.js:42:58)
    at AnimationProvider (node_modules/@mui/x-charts/context/AnimationProvider/AnimationProvider.js:21:24)
    at svg
    at eval (node_modules/@emotion/react/dist/emotion-element-832b737b.browser.cjs.js:71:23)
    at ChartsSurface (node_modules/@mui/x-charts/ChartsSurface/ChartsSurface.js:33:58)
    at HighlightedProvider (node_modules/@mui/x-charts/context/HighlightedProvider/HighlightedProvider.js:36:24)
    at InteractionProvider (node_modules/@mui/x-charts/context/InteractionProvider.js:72:20)
    at ZAxisContextProvider (node_modules/@mui/x-charts/context/ZAxisContextProvider.js:27:23)
    at CartesianProvider (node_modules/@mui/x-charts/context/CartesianProvider/CartesianProvider.js:24:17)
    at SeriesProvider (node_modules/@mui/x-charts/context/SeriesProvider/SeriesProvider.js:23:18)
    at PluginProvider (node_modules/@mui/x-charts/context/PluginProvider/PluginProvider.js:20:20)
    at DrawingProvider (node_modules/@mui/x-charts/context/DrawingProvider.js:50:21)
    at ChartContainer (node_modules/@mui/x-charts/ChartContainer/ChartContainer.js:32:430)
    at div
    at eval (node_modules/@emotion/react/dist/emotion-element-832b737b.browser.cjs.js:71:23)
    at ResponsiveChartContainer (node_modules/@mui/x-charts/ResponsiveChartContainer/ResponsiveChartContainer.js:25:230)
    at LineChart (node_modules/@mui/x-charts/LineChart/LineChart.js:37:58)
```

### Expected behavior

If the component is used incorrectly, an informative message should be provided. Currently the stacktrace / message displays an error internal to the component, as I am not setting any "horizontal-" keys explicitly anywhere, nor am I informed of what exactly I should be doing so the library will have enough information not to generate identical keys.

### Context

I'm trying to create a chart with one or multiple lines. I want the user to switch between a "linear" and a "log" scale for the YAxis values. While `scaleType` with "linear" works, it shows a warning for "log".

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
I noticed the issue in Firefox, and I managed to reproduce it in the CodeSandbox sample.

```
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.13.3 => 11.13.3
    @emotion/styled: 11.13.0 => 11.13.0
    @mui/core-downloads-tracker:  6.1.6
    @mui/icons-material: 6.1.6 => 6.1.6
    @mui/material: 6.1.6 => 6.1.6
    @mui/material-nextjs: 6.1.6 => 6.1.6
    @mui/private-theming:  6.1.6
    @mui/styled-engine:  6.1.6
    @mui/styles: 6.1.6 => 6.1.6
    @mui/system:  6.1.6
    @mui/types:  7.2.19
    @mui/utils:  6.1.6
    @mui/x-charts: 7.22.1 => 7.22.1
    @mui/x-charts-vendor:  7.20.0
    @mui/x-data-grid: 7.22.1 => 7.22.1
    @mui/x-internals:  7.21.0
    @types/react:  18.3.11
    react: next => 18.3.1
    react-dom: next => 18.3.1
    typescript: 5.6.3 => 5.6.3
```
</details>

**Search keywords**: "Warning: Encountered two children with the same key, `horizontal-`" when setting yAxis scaleType to "log"

**Comment by michelengelen** [comment]
Hey @dandrei and thanks for opening this issue.

I can confirm this and found the "culprit" here: https://github.com/mui/mui-x/blob/c499703166a050fece88dcc661dcaa3d14e4c61b/packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx#L28

The `formattedValue` comes from here: https://github.com/mui/mui-x/blob/c499703166a050fece88dcc661dcaa3d14e4c61b/packages/x-charts/src/hooks/useTicks.ts#L161

@JCQuintas would something like this be a solution? Is it safe to assume that each value is unique?

```diff
index 2827e782e..04eb4164b 100644
--- a/packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx
+++ b/packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx
@@ -23,9 +23,9 @@ export function ChartsGridHorizontal(props: ChartsGridHorizontalProps) {

   return (
     <React.Fragment>
-      {yTicks.map(({ formattedValue, offset }) => (
+      {yTicks.map(({ value, offset }) => (
         <GridLine
-          key={`horizontal-${formattedValue}`}
+          key={`horizontal-${value}`}
           y1={offset}
           y2={offset}
           x1={drawingArea.left}
```

**Comment by JCQuintas** [comment]
yeah, technically each value in the scale should be unique. The formatter is probably returning `''` in log mode, which is causing the current issue.

**Comment by dandrei** [comment]
@michelengelen thank you.

I have another related issue to report, namely that when the input series contains `null` values, the `linear` scale shows the data points correctly as simply missing, as per [this comment](https://github.com/mui/mui-x/pull/10801#issuecomment-1779200465), but the same scale when shown on a `log` scale will simply vanish, as if containing invalid data. 

I was trying to debug that issue when I stumbled upon the one I reported here, but I wasn't certain if it was related or not to the "Encountered two children with the same key".

Should I create a separate ticket for that? Please advise.

**Comment by michelengelen** [comment]
Hey @dandrei ... yes, a separate issue would be nice! 🙇🏼
