### ISSUE TITLE
[data grid] with `unstable_dataSource` fast clicking on navigation causing `Error: Minified React error #310`

### ISSUE THREAD

**Issue by TradeeHubDev** [mui/mui-x#15370]
### Steps to reproduce

Just click super fast on grid to navigate between pages

### Current behavior

![image](https://github.com/user-attachments/assets/ad344131-fb03-4045-8cdc-a02da40d3fc8)

```
8584-912256d4a34dc73e.js:1 Error: Minified React error #310; visit https://react.dev/errors/310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lP (6e4f7e7f-2d8a057eccaaaeae.js:1:42834)
    at Object.ar [as useMemo] (6e4f7e7f-2d8a057eccaaaeae.js:1:49816)
    at 8584-912256d4a34dc73e.js:2:60884
    at x (8584-912256d4a34dc73e.js:1:11951)
    at lb (6e4f7e7f-2d8a057eccaaaeae.js:1:41548)
    at aY (6e4f7e7f-2d8a057eccaaaeae.js:1:61275)
    at on (6e4f7e7f-2d8a057eccaaaeae.js:1:72678)
    at ui (6e4f7e7f-2d8a057eccaaaeae.js:1:111676)
    at 6e4f7e7f-2d8a057eccaaaeae.js:1:111527
    at uo (6e4f7e7f-2d8a057eccaaaeae.js:1:111535)
    at i3 (6e4f7e7f-2d8a057eccaaaeae.js:1:108663)
    at uF (6e4f7e7f-2d8a057eccaaaeae.js:1:128292)
    at MessagePort.T (8584-912256d4a34dc73e.js:1:103448)
overrideMethod	@	hook.js:608
(anonymous)	@	8584-912256d4a34dc73e.js:1
aO	@	6e4f7e7f-2d8a057eccaaaeae.js:1
aA	@	6e4f7e7f-2d8a057eccaaaeae.js:1
e.callback	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oP	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oN	@	6e4f7e7f-2d8a057eccaaaeae.js:1
o_	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oH	@	6e4f7e7f-2d8a057eccaaaeae.js:1
o4	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oH	@	6e4f7e7f-2d8a057eccaaaeae.js:1
o4	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oH	@	6e4f7e7f-2d8a057eccaaaeae.js:1
o4	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oH	@	6e4f7e7f-2d8a057eccaaaeae.js:1
o4	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oH	@	6e4f7e7f-2d8a057eccaaaeae.js:1
o4	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oH	@	6e4f7e7f-2d8a057eccaaaeae.js:1
o4	@	6e4f7e7f-2d8a057eccaaaeae.js:1
oH	@	6e4f7e7f-2d8a057eccaaaeae.js:1
(anonymous)	@	6e4f7e7f-2d8a057eccaaaeae.js:1
ud	@	6e4f7e7f-2d8a057eccaaaeae.js:1
i8	@	6e4f7e7f-2d8a057eccaaaeae.js:1
i3	@	6e4f7e7f-2d8a057eccaaaeae.js:1
uF	@	6e4f7e7f-2d8a057eccaaaeae.js:1
T	@	8584-912256d4a34dc73e.js:1
```

### Expected behavior

Not to error

### Context

I am using nextjs 15 with react 19 and MUI DataGridPro and when I am in production and press grid navigation very fast I get the error listed above I can't reproduce it in dev because nextjs probably too slow loading pages in dev build locally so my guess is from the super fast clicks something happening with my server side calls I do have a try catch in my method navigateGrid but not logging anything so my guess its probably something out of get rows not sure? 

```tsx
  const dataSource: GridDataSource = useMemo(() => {
    return {
      getRows: async (params) => {
        return await navigateGrid(params);
      }
      //getGroupKey: (row) => row.group,
      //getChildrenCount: (row) => row.descendantCount
    };
  }, [triggerGridFetch]);

  return (
    <DataGridPro
      unstable_dataSource={dataSource}
      unstable_dataSourceCache={dataSourceCache}
      columns={columns}
      apiRef={apiRef}
      loading={loading}
      checkboxSelection
      initialState={initialState}
      pageSizeOptions={[10, 20, 50, 100, 250, 500, 1000]} // Include the default page size in the options
      pagination
      paginationMode='server'
      onSortModelChange={handleSortModelChange}
      onRowClick={(params) => {
        if (onRowClick) {
          onRowClick(params.row);
        }
      }}
      disableRowSelectionOnClick
      columnVisibilityModel={columnVisibilityModel}
      onColumnVisibilityModelChange={(newModel) =>
        setColumnVisibilityModel(newModel)
      }
      onPaginationModelChange={handlePaginationModelChangeNavigation}
      slotProps={{
        pagination: {
          slotProps: {
            actions: {
              nextButton: {
                disabled: loading || !canNavigateGrid?.hasNextPage
              },
              previousButton: {
                disabled: loading || !canNavigateGrid?.hasPreviousPage
              }
            }
          }
        }
      }}
      slots={{
        toolbar: slots?.toolbar || GridToolbar
      }}
      getRowClassName={(params) =>
        params.indexRelativeToCurrentPage % 2 === 0 ? 'even-row' : 'odd-row'
      }
      sx={dataGridStyles}
      className={cn(
        'rounded-[--radius] border border-border shadow-sm',
        'dark:border-border dark:bg-card dark:text-primary-foreground'
      )}
    />
  );
```

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGridPro unstable_dataSource Minified React error #310

**Comment by michelengelen** [comment]
@cherniavskii is this maybe related to the race-condition we talked about?

**Comment by MBilalShafi** [comment]
@michelengelen This could be different since that one didn't result in a crash.

@TradeeHubDev could you prepare a minimal reproduction repo that I can clone, do a production build, and reproduce the error on?
It could also be something outside the Data Grid, so a reproduction example would be great.

Try to keep as little external code as possible so we can pinpoint the cause of the issue.
