### ISSUE TITLE
[DataGridPro] `sortingOrder` prop error when customising the `ColumnUnsortedIcon` component

### ISSUE THREAD

**Issue by joespeargresham** [mui/mui-x#4008]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Customising the ColumnUnsortedIcon component using the components prop causes an error in the console.

Snippet (please see [codesandbox ](https://codesandbox.io/s/datagridprodemo-material-demo-forked-nnb8ys?file=/demo.js)for full reproduction)
```
import { DataGridPro } from '@mui/x-data-grid-pro';
import SortIcon from '@mui/icons-material/Sort';

<DataGridPro
    {blah}
    components={{
        ColumnUnsortedIcon: SortIcon
    }} />
```

Error in console:
> Warning: React does not recognize the `sortingOrder` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `sortingorder` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at svg
    at eval (https://nnb8ys.csb.app/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:109:45)
    at SvgIcon (https://nnb8ys.csb.app/node_modules/@mui/material/SvgIcon/SvgIcon.js:66:43)
    at SortIcon
    at button
    at eval (https://nnb8ys.csb.app/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:109:45)
    at ButtonBase (https://nnb8ys.csb.app/node_modules/@mui/material/ButtonBase/ButtonBase.js:84:43)
    at eval (https://nnb8ys.csb.app/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:109:45)
    at IconButton (https://nnb8ys.csb.app/node_modules/@mui/material/IconButton/IconButton.js:90:43)
    at div
    at eval (https://nnb8ys.csb.app/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:109:45)
    at eval (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:4153:21)
    at eval (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:4167:21)
    at div
    at div
    at div
    at ja (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:4364:18)
    at div
    at eval (https://nnb8ys.csb.app/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:109:45)
    at eval (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:11083:22)
    at div
    at eval (https://nnb8ys.csb.app/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:109:45)
    at eval (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:11111:20)
    at eval (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:11149:17)
    at div
    at eval (https://nnb8ys.csb.app/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:109:45)
    at je (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:1876:14)
    at At (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:2045:20)
    at $t (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:2082:1)
    at zt (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:2104:20)
    at div
    at eval (https://nnb8ys.csb.app/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:109:45)
    at NoSsr (https://nnb8ys.csb.app/node_modules/@mui/base/NoSsr/NoSsr.js:12:20)
    at eval (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:4044:13)
    at eu (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:7412:54)
    at eval (https://nnb8ys.csb.app/node_modules/@mui/x-data-grid-pro/index-esm.js:11296:5)
    at div
    at DataGridProDemo (https://nnb8ys.csb.app/demo.js:34:60)
    at StyledEngineProvider (https://nnb8ys.csb.app/node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:18:23)

### Expected behavior 🤔

Customising the ColumnUnsortedIcon component should not cause an error.

### Steps to reproduce 🕹

https://codesandbox.io/s/datagridprodemo-material-demo-forked-nnb8ys?file=/demo.js

Steps:

1. Go to the code sandbox demo
2. Observe the error in the console

### Context 🔦

Trying to customise the ColumnUnsortedIcon icon without causing an error.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Chrome

  System:
    OS: Windows 10 10.0.17134
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 98.0.4758.82
    Edge: Spartan (42.17134.2208.0)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.66
    @mui/icons-material: ^5.3.1 => 5.3.1
    @mui/lab: ^5.0.0-alpha.66 => 5.0.0-alpha.66
    @mui/material: ^5.3.1 => 5.3.1
    @mui/private-theming:  5.3.0
    @mui/styled-engine:  5.3.0
    @mui/styles: ^5.3.0 => 5.3.0
    @mui/system: ^5.2.8 => 5.3.0
    @mui/types:  7.1.0
    @mui/utils:  5.3.0
    @mui/x-data-grid-pro: ^5.5.1 => 5.5.1
    @mui/x-license-pro:  5.5.1
    @types/react: ^17.0.38 => 17.0.38
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.5.5 => 4.5.5

```
</details>

### Order ID 💳 (optional)

#27566

**Comment by DanailH** [comment]
Hi @joespeargresham thanks for raising this. The problem seems to originate from here https://github.com/mui/mui-x/pull/3449. The reason is that you may want to change the sorting direction sequence, that's why this prop is passed to the `ColumnUnsortedIcon` slot. In our examples, the unsorted icon shows what would be the next sorting direction.
Either way, you can fix the problem by only passing the needed props
```
ColumnUnsortedIcon: ({sortingOrder, ...other}) => <SortIcon {...other} />,
```
