### ISSUE TITLE
GridActionsCell - Error when Using Cancel Button to Leave 'Edit' State

### ISSUE THREAD

**Issue by ScotlandBard** [mui/mui-x#4675]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When editing a grid in 'row' mode and canceling an edit (returning to 'view' mode), the grid displays "An error occurred." and data is no longer visible. 

### Expected behavior 🤔

The row being edited should be returned to 'view' mode, and data should still be visible.

### Steps to reproduce 🕹

Codesandbox: https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-rw0dbu?file=/demo.tsx

Steps:

1. Click the edit button on any row to enter edit mode.
2. Click the cancel button to return to view mode.

When canceling, and error is generated from this useEffect call:

```
React.useEffect(() => {
    if (focusedButtonIndex >= 0) {
      const child = rootRef.current?.children[focusedButtonIndex] as HTMLElement;
      child.focus();
    }
  }, [focusedButtonIndex]);
```

Console Output:
```
MUI: GridErrorHandler - An unexpected error occurred. Error: Cannot read properties of undefined (reading 'focus').  TypeError: Cannot read properties of undefined (reading 'focus')
    at eval (GridActionsCell.js:59:13)
    at commitHookEffectListMount (react-dom.development.js:23049:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24816:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24781:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24768:7)
    at commitPassiveMountEffects (react-dom.development.js:24756:3)
    at flushPassiveEffectsImpl (react-dom.development.js:26990:3)
    at flushPassiveEffects (react-dom.development.js:26935:14)
    at commitRootImpl (react-dom.development.js:26886:5)
    at commitRoot (react-dom.development.js:26638:5)
    at performSyncWorkOnRoot (react-dom.development.js:26073:3)
    at flushSyncCallbacks (react-dom.development.js:12009:22)
    at eval (react-dom.development.js:25607:13) undefined 
    in ErrorBoundary (created by GridErrorHandler)
    in GridErrorHandler (created by DataGridPro)
    in DataGridPro (created by DataGridPro)
    in DataGridPro (created by FullFeaturedCrudGrid)
    in FullFeaturedCrudGrid
```

### Context 🔦

This issue prevents a user from viewing or editing a grid until the page is refreshed. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:

    OS: Windows 10 10.0.19043

  Binaries:

    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE

    Yarn: Not Found

    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD

  Browsers:

    Chrome: Not Found

    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.50)

  npmPackages:

    @emotion/react: ^11.6.0 => 11.9.0

    @emotion/styled: ^11.6.0 => 11.8.1

    @mui/base:  5.0.0-alpha.78

    @mui/icons-material: ^5.1.1 => 5.6.2

    @mui/material: ^5.2.8 => 5.6.3

    @mui/private-theming:  5.6.2

    @mui/styled-engine:  5.6.1

    @mui/system:  5.6.3

    @mui/types:  7.1.3

    @mui/utils:  5.6.1

    @mui/x-data-grid:  5.10.0

    @mui/x-data-grid-pro: ^5.6.1 => 5.10.0

    @mui/x-date-pickers:  5.0.0-alpha.2

    @mui/x-date-pickers-pro: ^5.0.0-alpha.0 => 5.0.0-alpha.2

    @mui/x-license-pro: ^5.7.0 => 5.10.0

    @types/react:  17.0.44

    react: ^17.0.2 => 17.0.2

    react-dom: ^17.0.2 => 17.0.2

    typescript:  4.6.3
```
</details>

Tested in Microsoft Edge.

This feature last worked as expected in @mui/x-data-grid-pro 5.6.1.

### Order ID 💳 (optional)

36108

**Comment by m4theushw** [comment]
Will be fixed by #4694
