### ISSUE TITLE
Cannot find variable document (MobileDatePicker) React Native

### ISSUE THREAD

**Issue by OnlyRealNubs** [mui/mui-x#5141]
Ever since I have installed miu/lab and @emotion I have been getting this error in react 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I get a red error popup in my terminal saying 
```
ReferenceError: Can't find variable: document
at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:172:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules\metro-runtime\src\polyfills\require.js:204:6 in guardedLoadModule
at http://192.168.2.10:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:222513:3 in global code
```

## Expected Behavior 🤔

It should not give me any errors.

## Steps to Reproduce 🕹

Steps:

1. Run `npm install @mui/material @emotion/react @emotion/styled`, `npm install @mui/lab` and `npm install @mui/material`
2. import `TextField from '@mui/material/TextField'` and `MobileDatePicker from '@mui/lab/MobileDatePicker'`
3. type 'npm start' into the terminal
4. open up the simulation on a device either android or iOS

## Your Environment 🌎
```
import React, {useState} from 'react'
import { StyleSheet, Text, View, TextInput, TouchableHighlight } from 'react-native';
import Topbar from "../components/topbarSplash"
import Constants from 'expo-constants'
import MobileDatePicker from '@mui/lab/MobileDatePicker';
import AdapterLuxon from '@mui/lab/AdapterLuxon';
import TextField from '@mui/material/TextField';

function SignUp() {

    const [date, setDate] = useState(new Date())
    const [open, setOpen] = useState(false)

    let usern = ""
    let pass = ""
    let passc = ""
    let email = ""

    const comp = {
        username : usern,
        password: pass,
        email: email,
        bday: null
    }

        return (
            <View style={styles.container}>
                <View style={styles.statusBar} />
                <Topbar></Topbar>
                <View style={styles.contentContainer}>
                    <View style={styles.divContainer}>
                        <Text style={styles.h1}>SignUp</Text>
                        <View style={styles.inputContainer}>
                            <View style={styles.inputItemContainer}>
                                <TextInput autoFocus={false} textContentType={"username"} returnKeyType={'next'} placeholder={"Username"} style={styles.inputItem}/>
                            </View>
                            <View style={styles.inputItemContainer}>
                                <TextInput autoFocus={false} secureTextEntry={true} textContentType={"newPassword"} returnKeyType={'next'} placeholder={"Password"} style={styles.inputItem}/>
                            </View>
                            <View style={styles.inputItemContainer}>
                                <TextInput autoFocus={false} secureTextEntry={true} textContentType={"password"} returnKeyType={'next'} placeholder={"Confirm Password"} style={styles.inputItem}/>
                            </View>
                            <View style={styles.inputItemContainer}>
                                <TouchableHighlight style={styles.inputItem} onPress={()=> {setOpen(true)}}><Text>Birthday: {date.getFullYear().toString()}-{date.getUTCMonth().toString()}-{date.getDay().toString()}</Text></TouchableHighlight>
  /* =========>*/                              <MobileDatePicker label="Birthday" value={value} maxDate={new Date()} renderInput={(params) => <TextField {...params} />}/>
                            </View>
                            <View style={styles.inputItemContainer}>
                                <TextInput autoFocus={false} textContentType={"emailAddress"} keyboardType={"email-address"} returnKeyType={'done'} placeholder={"Email"} style={styles.inputItem}/>
                            </View>
                            <View style={styles.inputItemContainer}>
                                <TouchableHighlight underlayColor='#e0e00d' style={styles.submitButton} onPress={()=> {console.log('press')}}>
                                    <Text style={styles.buttonText}>Sign Up</Text>
                                </TouchableHighlight>
                            </View>
                        </View>
                    </View>
                </View>
            </View>
        )
       
}
```

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
> open up the simulation on a device either android or iOS

I would need more detailed about this step
But if, at any point, you are using React Native, we do not support it.
