### ISSUE TITLE
Grid Action cell item showInMenuNotWorking 

### ISSUE THREAD

**Issue by mk2s6** [mui/mui-x#5146]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When add column of actions to datagrid component it is throwing error related to showInMenu item options

MUI: GridErrorHandler - An unexpected error occurred. Error: Cannot read properties of undefined (reading 'showInMenu').  TypeError: Cannot read properties of undefined (reading 'showInMenu')
    at GridActionsCell.js:81:1
    at Array.filter (<anonymous>)
    at GridActionsCell (GridActionsCell.js:81:1)
    at renderWithHooks (react-dom.development.js:14992:1)
    at mountIndeterminateComponent (react-dom.development.js:17820:1)
    at beginWork (react-dom.development.js:19056:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3952:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4001:1)
    at invokeGuardedCallback (react-dom.development.js:4063:1)
    at beginWork$1 (react-dom.development.js:23971:1) undefined 
    at ErrorBoundary (http://localhost:3001/main.d09ad872d41f9d3e44d5.hot-update.js:10179:1)
    at GridErrorHandler (http://localhost:3001/main.d09ad872d41f9d3e44d5.hot-update.js:11659:5)
    at div
    at http://localhost:3001/static/js/bundle.js:6842:66
    at GridRoot (http://localhost:3001/main.d09ad872d41f9d3e44d5.hot-update.js:15281:100)
    at GridContextProvider (http://localhost:3001/main.d09ad872d41f9d3e44d5.hot-update.js:19517:5)
    at DataGrid (http://localhost:3001/main.d09ad872d41f9d3e44d5.hot-update.js:8061:84)
    at DataTable (http://localhost:3001/main.8e85accfd135e07c707e.hot-update.js:36:5)

### Expected behavior 🤔

It show show in menu list regarding the operations

### Steps to reproduce 🕹

Steps:

1. Add a column type Actions in datagrid 
2. pass GridActionCellItem component as an action item as in documentation
3. an error is thrown
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
Browser Chrome: Chrome
  "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@mui/icons-material": "^5.8.2",
    "@mui/material": "^5.8.2",
    "@mui/x-data-grid": "^5.12.0",
    "@mui/x-data-grid-generator": "^5.12.0",
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
@mk2s6 I do not manage to reproduce your error message. Could you provide a reproduction example? This codesandbox might be a good starting point:

https://codesandbox.io/s/columntypesgrid-material-demo-forked-iekvg3?file=/demo.tsx
