### ISSUE TITLE
[CalendarPicker] Setting initial state value causes error

### ISSUE THREAD

**Issue by n1xn** [mui/mui-x#5187]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Setting the initial state of the selectedDate causes `CalendarPicker` to crash. The initial state has always to be null, so I am not able to preselect a day when the component mounts.

```jsx
const firstAvailableSlotDay = (appointmentSlots && appointmentSlots[0].dateFrom) || null;
const [selectedDate, setSelectedDate] = React.useState<Date | null>(firstAvailableSlotDay);

return (
	  <CalendarPicker
		  date={selectedDate}
		  onChange={(newDate) => handleDatePickerSelection(newDate)}
		  shouldDisableDate={disableUnavailableDates}
	  />
)
```

```
index.esm.js:218 
        
       Uncaught TypeError: date.startOf is not a function
    at DayjsUtils.startOfMonth (index.esm.js:218:1)
    at useCalendarState (useCalendarState.js:58:1)
    at CalendarPicker (CalendarPicker.js:109:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at updateForwardRef (react-dom.development.js:20023:1)
    at beginWork (react-dom.development.js:22465:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at beginWork$1 (react-dom.development.js:27405:1)
DayjsUtils.startOfMonth @ index.esm.js:218
useCalendarState @ useCalendarState.js:58
CalendarPicker @ CalendarPicker.js:109
renderWithHooks @ react-dom.development.js:16175
updateForwardRef @ react-dom.development.js:20023
beginWork @ react-dom.development.js:22465
callCallback @ react-dom.development.js:4161
invokeGuardedCallbackDev @ react-dom.development.js:4210
invokeGuardedCallback @ react-dom.development.js:4274
beginWork$1 @ react-dom.development.js:27405
performUnitOfWork @ react-dom.development.js:26513
workLoopSync @ react-dom.development.js:26422
renderRootSync @ react-dom.development.js:26390
recoverFromConcurrentError @ react-dom.development.js:25806
performConcurrentWorkOnRoot @ react-dom.development.js:25706
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18572 
        
       The above error occurred in the <ForwardRef(CalendarPicker)> component:

    at CalendarPicker (http://localhost:3000/static/js/bundle.js:25456:85)
    at div
    at div
    at AppointmentPicker (http://localhost:3000/static/js/bundle.js:333:5)
    at div
    at div
    at main
    at MainLayout (http://localhost:3000/static/js/bundle.js:1884:5)
    at ExtraDetailsPage (http://localhost:3000/static/js/bundle.js:2722:81)
    at Routes (http://localhost:3000/static/js/bundle.js:120241:5)
    at Router (http://localhost:3000/static/js/bundle.js:120174:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:118983:5)
    at LocalizationProvider (http://localhost:3000/static/js/bundle.js:28068:81)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18572
update.callback @ react-dom.development.js:18605
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23290
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25848
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
index.esm.js:218 
        
       Uncaught TypeError: date.startOf is not a function
    at DayjsUtils.startOfMonth (index.esm.js:218:1)
    at useCalendarState (useCalendarState.js:58:1)
    at CalendarPicker (CalendarPicker.js:109:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at updateForwardRef (react-dom.development.js:20023:1)
    at beginWork (react-dom.development.js:22465:1)
    at beginWork$1 (react-dom.development.js:27381:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
    at renderRootSync (react-dom.development.js:26390:1)
```

### Expected behavior 🤔

Not crashing & having the option to set a date for the `CalendarPicker` initial without using it.

### Steps to reproduce 🕹

Steps:

1. Install ```    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@mui/material": "^5.6.4",
    "@mui/x-date-pickers": "^5.0.0-alpha.2",```
2. Use the LocalitzationAdapter with `AdapterDayJs`
3. Crashing in my component by having ```const [selectedDate, setSelectedDate] = React.useState<Date | null>(firstAvailableSlotDay);```

### Context 🔦

In my programm I want to help the user by automatically selecting the first available date from my appointments instead of waiting for the user to select a date in the `CalendarPicker`

### Your environment 🌎

<details>
<summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.47)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.79
    @mui/material: ^5.6.4 => 5.6.4
    @mui/private-theming:  5.6.2
    @mui/styled-engine:  5.6.1
    @mui/system:  5.6.4
    @mui/types:  7.1.3
    @mui/utils:  5.6.1
    @mui/x-date-pickers: ^5.0.0-alpha.2 => 5.0.0-alpha.6
    @types/react: ^18.0.7 => 18.0.8
    react: ^18.1.0 => 18.1.0
    react-dom: ^18.1.0 => 18.1.0
    styled-components: ^5.3.5 => 5.3.5
    typescript: ^4.6.3 => 4.6.4
```
</details>

**Comment by alexfauquette** [comment]
The problem seems to come from the value we do not pars. using directly a date object from dayjs should solve your problem

```js
const firstAvailableSlotDay = adapter.date(new Date(2024, 10, 10))
```

https://codesandbox.io/s/materialuipickers-demo-mui-x-forked-oeum92?file=/demo.tsx

**Comment by flaviendelangle** [comment]
Closing this one
Related to #5759

**Comment by mkonars** [comment]
@alexfauquette 
The types are wrong, you can also see it in your sandbox.

```
const firstAvailableSlotDay: dayjs.Dayjs
Argument of type 'Dayjs' is not assignable to parameter of type 'Date | (() => Date)'.
  Type 'Dayjs' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 36 more.ts(2345)
```

It will work if you cast the type
`(adapter.date(props.minDateTime) as unknown as Date)`

Just writing it in case anyone wants to use it. I have moved to AdapterDateFns, which does not have this issue.
