### ISSUE TITLE
[question] DataGrid custom filter + serverside filtering gives apiRef.current.getLocaleText(...) is not a function

### ISSUE THREAD

**Issue by philjones88** [mui/mui-x#5344]
### Order ID 💳

44827

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We're trying to combine:

https://mui.com/x/react-data-grid/filtering/#custom-input-component

with:

https://mui.com/x/react-data-grid/filtering/#server-side-filter

but we're hitting this error when the filter panel is closed. The filter is applied and the grid is updated before you close the panel, so that works.

```
chunk-IJJFWVHW.js?v=6a1288aa:6905 Uncaught TypeError: apiRef.current.getLocaleText(...) is not a function
    at chunk-IJJFWVHW.js?v=6a1288aa:6905:77
    at updateMemo (react-dom.development.js:15867:19)
    at Object.useMemo (react-dom.development.js:16413:16)
    at Object.useMemo (react.development.js:1532:21)
    at GridToolbarFilterButton2 (chunk-IJJFWVHW.js?v=6a1288aa:6896:38)
    at renderWithHooks (react-dom.development.js:14985:18)
    at updateForwardRef (react-dom.development.js:17044:20)
    at beginWork (react-dom.development.js:19098:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
```

```
The above error occurred in the <ForwardRef(GridToolbarFilterButton2)> component:

    at GridToolbarFilterButton2 (https://localhost:4443/node_modules/.vite/deps/chunk-IJJFWVHW.js?v=6a1288aa:6884:5)
    at div
    at https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:3397:50
    at GridToolbarContainer2 (https://localhost:4443/node_modules/.vite/deps/chunk-IJJFWVHW.js?v=6a1288aa:2959:5)
    at DevicesToolbar
    at div
    at GridHeader2 (https://localhost:4443/node_modules/.vite/deps/chunk-IJJFWVHW.js?v=6a1288aa:7396:21)
    at div
    at GridHeaderPlaceholder (https://localhost:4443/node_modules/.vite/deps/chunk-IJJFWVHW.js?v=6a1288aa:879:18)
    at ErrorBoundary (https://localhost:4443/node_modules/.vite/deps/chunk-IJJFWVHW.js?v=6a1288aa:798:21)
    at GridErrorHandler (https://localhost:4443/node_modules/.vite/deps/chunk-IJJFWVHW.js?v=6a1288aa:830:5)
    at div
    at https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:3397:50
    at GridRoot2 (https://localhost:4443/node_modules/.vite/deps/chunk-IJJFWVHW.js?v=6a1288aa:2781:21)
    at GridContextProvider (https://localhost:4443/node_modules/.vite/deps/chunk-IJJFWVHW.js?v=6a1288aa:12125:3)
    at DataGridPro
    at DevicesGrid (https://localhost:4443/src/components/Pages/Devices/DevicesGrid.tsx?t=1656502405200:31:18)
    at div
    at https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:3397:50
    at Box3 (https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:5764:19)
    at https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:3397:50
    at I18nWrapper (https://localhost:4443/src/components/Wrappers/I18nWrapper/I18nWrapper.tsx:21:3)
    at Devices (https://localhost:4443/src/components/Pages/Devices/Devices.tsx?t=1656502405200:27:7)
    at Routes (https://localhost:4443/node_modules/.vite/deps/react-router-dom.js?v=6a1288aa:1122:5)
    at AppRoutes
    at div
    at https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:3397:50
    at Box3 (https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:5764:19)
    at https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:3397:50
    at div
    at https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:3397:50
    at Box3 (https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:5764:19)
    at https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:3397:50
    at Router (https://localhost:4443/node_modules/.vite/deps/react-router-dom.js?v=6a1288aa:1069:15)
    at HashRouter (https://localhost:4443/node_modules/.vite/deps/react-router-dom.js?v=6a1288aa:1224:5)
    at SnackbarProvider2 (https://localhost:4443/node_modules/.vite/deps/notistack.js?v=6a1288aa:624:24)
    at InnerThemeProvider (https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:5705:17)
    at ThemeProvider2 (https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:5454:5)
    at ThemeProvider3 (https://localhost:4443/node_modules/.vite/deps/chunk-PEV6EOSM.js?v=6a1288aa:5713:5)
    at App (https://localhost:4443/src/components/App/App.tsx?t=1656502405200:42:7)
    at I18nextProvider (https://localhost:4443/node_modules/.vite/deps/react-i18next.js?v=6a1288aa:857:19)
    at P (https://localhost:4443/node_modules/.vite/deps/@vqcomms_oidc-client-rtk.js?v=6a1288aa:3235:14)
    at AppContextProvider (https://localhost:4443/src/providers/AppContextProvider.tsx:23:3)
    at PersistGate2 (https://localhost:4443/node_modules/.vite/deps/redux-persist_integration_react.js?v=6a1288aa:90:5)
    at Provider (https://localhost:4443/node_modules/.vite/deps/chunk-NFFX5CEO.js?v=6a1288aa:166:20)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary
```

```
MUI: GridErrorHandler - An unexpected error occurred. Error: apiRef.current.getLocaleText(...) is not a function.  TypeError: apiRef.current.getLocaleText(...) is not a function
    at chunk-IJJFWVHW.js?v=6a1288aa:6905:77
    at updateMemo (react-dom.development.js:15867:19)
    at Object.useMemo (react-dom.development.js:16413:16)
    at Object.useMemo (react.development.js:1532:21)
    at GridToolbarFilterButton2 (chunk-IJJFWVHW.js?v=6a1288aa:6896:38)
    at renderWithHooks (react-dom.development.js:14985:18)
    at updateForwardRef (react-dom.development.js:17044:20)
    at beginWork (react-dom.development.js:19098:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16) undefined
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Brave browser
```

```
  System:
    OS: macOS 11.4
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Edge: Not Found
    Firefox: 101.0.1
    Safari: 14.1.1
  npmPackages:
    @emotion/react: ^11.8.2 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/icons-material: ^5.5.1 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.84 => 5.0.0-alpha.86 
    @mui/material: ^5.8.6 => 5.8.6 
    @mui/styled-engine:  5.8.0 
    @mui/system: ^5.8.6 => 5.8.6 
    @mui/utils:  5.8.4 
    @mui/x-data-grid:  5.12.3 
    @mui/x-data-grid-pro: ^5.12.3 => 5.12.3 
    @mui/x-license-pro: ^5.12.3 => 5.12.3 
    @types/react: ^17.0.39 => 17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.6.3 => 4.7.4 
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.
