### ISSUE TITLE
Uncaught TypeError: getColumns is not a function

### ISSUE THREAD

**Issue by MatthewMcP** [mui/mui-x#5974]
### Order ID 💳

46063

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Having a strange issue as the error stack below describes. We're using MUI-pro within our component library but this error is only showing within the project using this component library. This has been working previously but has stopped working last Friday. Let me know if you need more info

`Uncaught TypeError: getColumns is not a function
    at DataGridProColumnHeaders (index.esm.js:5259:17)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19221:20)
    at beginWork (react-dom.development.js:21631:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27446:7)
    at performUnitOfWork (react-dom.development.js:26555:12)
    at workLoopSync (react-dom.development.js:26461:5)
    he above error occurred in the <ForwardRef(DataGridProColumnHeaders)> component:

    at DataGridProColumnHeaders (webpack://cdm-mod/./node_modules/cdm-shared/lib/index.esm.js?:5185:5)
    at div
    at eval (webpack://cdm-mod/./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js?:57:66)
    at GridMainContainer (webpack://cdm-mod/./node_modules/@mui/x-data-grid/components/containers/GridMainContainer.js?:42:100)
    at GridBody (webpack://cdm-mod/./node_modules/@mui/x-data-grid/components/base/GridBody.js?:31:5)
    at ErrorBoundary (webpack://cdm-mod/./node_modules/@mui/x-data-grid/components/ErrorBoundary.js?:8:1)
    at GridErrorHandler (webpack://cdm-mod/./node_modules/@mui/x-data-grid/components/base/GridErrorHandler.js?:28:5)
    at div
    at eval (webpack://cdm-mod/./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js?:57:66)
    at GridRoot (webpack://cdm-mod/./node_modules/@mui/x-data-grid/components/containers/GridRoot.js?:57:100)
    at GridContextProvider (webpack://cdm-mod/./node_modules/@mui/x-data-grid/context/GridContextProvider.js?:15:3)
    at DataGridPro (webpack://cdm-mod/./node_modules/cdm-shared/lib/index.esm.js?:5295:17)....`

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
 "@mui/x-data-grid-pro": "5.14.0".
 Using Chrome
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```

Running the above command for info does not return
</details>

**Comment by MatthewMcP** [comment]
This has been resolved, I'm not 100% what the cause was. It seems to be relating to using mui datagrid within peer dependencies and using mui-datagrid-pro elsewhere. Closing
