### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by shrikantpardhi** [mui/mui-x#5977]
I'm getting the below warning when I use DataGrid in Mui v5.
```

Warning: Each child in a list should have a unique "key" prop.

Check the render method of `GridRow`. See https://reactjs.org/link/warning-keys for more information.
    at IconButton (http://localhost:3000/static/js/2.chunk.js:34335:85)
    at GridRow (http://localhost:3000/static/js/2.chunk.js:84490:24)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridVirtualScrollerRenderZone (http://localhost:3000/static/js/2.chunk.js:95059:25)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridVirtualScrollerContent (http://localhost:3000/static/js/2.chunk.js:94986:25)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridVirtualScroller (http://localhost:3000/static/js/2.chunk.js:94920:25)
    at DataGridVirtualScroller (http://localhost:3000/static/js/2.chunk.js:83714:25)
    at div
    at AutoSizer (http://localhost:3000/static/js/2.chunk.js:83921:24)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridMainContainer (http://localhost:3000/static/js/2.chunk.js:89550:105)
    at GridBody (http://localhost:3000/static/js/2.chunk.js:85199:24)
    at ErrorBoundary (http://localhost:3000/static/js/2.chunk.js:83768:173)
    at GridErrorHandler (http://localhost:3000/static/js/2.chunk.js:85313:24)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridRoot (http://localhost:3000/static/js/2.chunk.js:89714:106)
    at GridContextProvider (http://localhost:3000/static/js/2.chunk.js:95436:21)
    at DataGrid (http://localhost:3000/static/js/2.chunk.js:81496:89)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at Box (http://localhost:3000/static/js/2.chunk.js:76268:74)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at Box (http://localhost:3000/static/js/2.chunk.js:76268:74)
    at ExamsPage (http://localhost:3000/static/js/main.chunk.js:3417:75)
    at Routes (http://localhost:3000/static/js/2.chunk.js:171488:24)
    at Router (http://localhost:3000/static/js/2.chunk.js:171413:30)
    at BrowserRouter (http://localhost:3000/static/js/2.chunk.js:170139:23)
    at ThemeProvider (http://localhost:3000/static/js/2.chunk.js:71776:24)
    at App (http://localhost:3000/static/js/main.chunk.js:126:73)

```
below code, I'm using
```
<DataGrid
          rows={rows}
          columns={columns}
          pageSize={5}
          rowsPerPageOptions={[5]}
          checkboxSelection
          disableSelectionOnClick
          experimentalFeatures={{ newEditingApi: true }}
        />
```

**Comment by shrikantpardhi** [comment]
Duplicate of #5968

**Comment by Stas-Buzunko** [comment]
I've got these 2 warnings when one of my columns has only valueGetter without field property.
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `ForwardRef(GridColumnsHeaders)`.
Check the render method of `ForwardRef(GridRow)`.
```
Adding "field" property fixed these warnings

**Comment by scd8418** [comment]
Thanks for @Stas-Buzunko comment above. It appears you need a 'field' property even if you have a renderCell. Adding the field property fixed it for me as well.
