### ISSUE TITLE
[data grid] Event that indicates grid rows are ready / re-rendered

### ISSUE THREAD

**Issue by MorMeshulam** [mui/mui-x#6361]
### Summary 💡

Hi,
i found the grid logger very helpful to track after changes but
i cant find a way to catch the rows changing moment after sorting and filtering ends entirley.

is there any way to figure it out with the current api ?
is there any onGridReady event in the up coming versions ?

best regards,
mor meshulam.

**Comment by DanailH** [comment]
Hi, @MorMeshulam thanks for asking this!
You are right, I don't see an exposed event that allows users to know when the rows finish updating. We have some events that do that but they are internal and we haven't exposed/documented them.

On another note - can you elaborate more about the `onGridReady` callback (or just an event) you mentioned? When do you see it being called?

**Comment by MorMeshulam** [comment]
Thanks for your answer,I see it called any time when the grid data or definition changes.it suppose to be called when that change is completely ends and the grid is ready with the new configuration and data (after all state changes ends).best regards mor Sent from my Mor’s iPhoneOn 5 Oct 2022, at 12:34, Danail Hadjiatanasov ***@***.***> wrote:﻿
Hi, @MorMeshulam thanks for asking this!
You are right, I don't see an exposed event that allows users to know when the rows finish updating. We have some events that do that but they are internal and we haven't exposed/documented them.
On another note - can you elaborate more about the onGridReady callback (or just an event) you mentioned? When do you see it being called?

**Comment by MorMeshulam** [comment]
another important thing,why we can't know exactly which piece of state had changed in the onStateChange event?this event is the only event that allow us the get close to the grid changes,but he fires many times on each event with no way to figure what actually happened or changes on each phase like 'update filter' or 'visible rows set' etc.something exactly like I expected from the logger to share.:)Sent from my Mor’s iPhoneOn 5 Oct 2022, at 15:44, Mor Meshulam ***@***.***> wrote:﻿Thanks for your answer,I see it called any time when the grid data or definition changes.it suppose to be called when that change is completely ends and the grid is ready with the new configuration and data (after all state changes ends).best regards mor Sent from my Mor’s iPhoneOn 5 Oct 2022, at 12:34, Danail Hadjiatanasov ***@***.***> wrote:﻿
Hi, @MorMeshulam thanks for asking this!
You are right, I don't see an exposed event that allows users to know when the rows finish updating. We have some events that do that but they are internal and we haven't exposed/documented them.
On another note - can you elaborate more about the onGridReady callback (or just an event) you mentioned? When do you see it being called?

**Comment by SolomidHero** [comment]
@DanailH @m4theushw 
Another use case: I found it tricky to scroll at the last index column. It would be much better to understand when I can scroll via API, because otherwise I get:
```
TypeError: Cannot read properties of null (reading 'scrollLeft')
    at Object.scrollToIndexes (http://localhost:8389/build/routes/dashboard-RXED22JP.js:45302:61)
    at http://localhost:8389/build/routes/dashboard-RXED22JP.js:65052:39
    ...
```

my code:
```
  useEffect(() => {
    if (apiRef.current.scrollToIndexes) {
      apiRef.current.scrollToIndexes?.({
        rowIndex: 0,
        colIndex: columns.length - 1,
      });
    }
  }, [apiRef, columns]);
```

**Comment by michelengelen** [comment]
Status update: `filteredRowsSet` and `sortedRowsSet` mentioned above still exist internally but remain undocumented and unstable, so nothing has changed on that front since 2022.

This thread has picked up a few different asks since the original question though: a generic "grid settled" signal, fetching extra data for visible rows after sort/filter, and safely knowing when it's OK to call `apiRef.current.scrollToIndexes`. These are different enough problems that a single event won't cleanly solve all of them, and some may already have better answers today, for example the Data Source lazy-loading APIs for on-demand row data.

Could each of you confirm whether your specific use case is still unmet on the latest version? If so, please open a focused issue per use case; that's much easier for us to scope and prioritize than one broad "ready" event request.

Keeping this open until that split happens.

**Comment by michelengelen** [comment]
Following up on my earlier comment, I dug into this and I think we can solve the core ask here without adding any new prop or event.

The grid already fires exactly the events this thread is asking for, they've just been kept out of the docs: `rowsSet`, `filteredRowsSet` and `sortedRowsSet`. The plan is to promote them to the [public events catalog](https://mui.com/x/react-data-grid/events/#catalog-of-events) as-is:

```tsx
apiRef.current.subscribeEvent('sortedRowsSet', () => {
  const visibleRowIds = gridExpandedSortedRowIdsSelector(apiRef);
  // ...
});
```

A few things have changed since this issue was opened that make this viable now:
- `useGridApiRef` and `subscribeEvent` are available on the Community plan since v7, so the earlier "you may need a Pro license" caveat no longer applies.
- These event names are already part of the public surface anyway: the documented default of the Premium `historyValidationEvents` prop lists all three.

On semantics, since that was part of the confusion around `onStateChange`: each event fires synchronously right after the corresponding state is committed, before React re-renders. Inside a handler, selectors return the fresh row order, but the DOM is not updated yet. A filter change fires only `filteredRowsSet`, a sort change only `sortedRowsSet`, and a rows update fires `rowsSet` -> `filteredRowsSet` -> `sortedRowsSet` in that order. We'll document this on the events page.

Mapping to the use cases collected in this thread:

- "Rows changed after sort/filter ends" (original ask): subscribe to `filteredRowsSet` + `sortedRowsSet`.
- Fetching extra data for visible rows (@alaqs): same events, read the visible rows via selectors in the handler. Also worth a look: the server-side data source now covers on-demand row data natively.
- Knowing when `scrollToIndexes` is safe (@SolomidHero): the `rootMount` event is already public and fires when the grid's root element becomes available.
- DOM actually re-rendered: that's what `renderedRowsIntervalChange` (already public) is for; the state events above intentionally fire before the render.

If someone still needs a single aggregated "visible rows changed" event that also covers pagination and row expansion, please open a focused issue for that so we can gauge demand separately.

Thoughts on that @mui/grid ?
cc @JCQuintas
