### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by robertjustjones** [mui/mui-x#6847]
### Order ID 💳

53925

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm using DataGridPremium and the Excel Export. Works fine localhost, but I'm getting a JS console log error in Chrome.

```
excelSerializer.js:256 Uncaught (in promise) TypeError: f.Workbook is not a constructor
    at excelSerializer.js:256:20
    at s (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at ye (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:22:9)
```

How do I fix this?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 11.6.8
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Edge: Not Found
    Firefox: 43.0.4
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.5
    @emotion/styled: ^11.10.4 => 11.10.5
    @mui/base:  5.0.0-alpha.105
    @mui/core-downloads-tracker:  5.10.13
    @mui/icons-material: ^5.10.3 => 5.10.9
    @mui/lab: ^5.0.0-alpha.103 => 5.0.0-alpha.107
    @mui/material: ^5.10.5 => 5.10.13
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/system:  5.10.13
    @mui/types:  7.2.0
    @mui/utils:  5.10.9
    @mui/x-data-grid:  5.17.11
    @mui/x-data-grid-generator: ^5.17.10 => 5.17.11
    @mui/x-data-grid-premium: ^5.17.10 => 5.17.11
    @mui/x-data-grid-pro:  5.17.11
    @mui/x-license-pro:  5.17.11
    @types/react: ^18.0.0 => 18.0.25
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.4.2 => 4.8.4```
</details>

**Comment by cherniavskii** [comment]
Hey @robertjustjones 
This looks like missing `exceljs` for some reason.
Can you provide a reproduction example?
It seems to work fine in our docs: https://mui.com/x/react-data-grid/export/#excel-export
