### ISSUE TITLE
[data grid] When using the new multi-column aggregation feature, I'm getting a maxiumum call stack size exceeded error

### ISSUE THREAD

**Issue by gavbrennan** [mui/mui-x#6944]
### Order ID 💳

50374

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Here's my aggregation function - is there anything obvious I'm doing wrong?

    const ABWeigtedAgg: GridAggregationFunction<{ A: number; B: number }, number> = {
        label: 'ABWeigtedAgg',
        getCellValue: ({ row }) => ({ A: row.A, B: row.B}),
        apply: ({ values }) => {
            let AB= 0;
            let B = 0;
            values.forEach((value) => {
                if (value) {
                    AB+= value.A* value.B;
                    B+= value.B;
                }
            });
            return AB / B;
        },
        columnTypes: ['number'],
    };

Call stack:
Uncaught RangeError RangeError: Maximum call stack size exceeded
    at selector (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\utils\createSelector.js:12:1)
    at dependenciesChecker (c:\GIT\Pltfm\client\pltfm\node_modules\reselect\es\index.js:77:1)
    at memoized (c:\GIT\Pltfm\client\pltfm\node_modules\reselect\es\defaultMemoize.js:123:1)
    at selector (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\utils\createSelector.js:35:1)
    at dependenciesChecker (c:\GIT\Pltfm\client\pltfm\node_modules\reselect\es\index.js:77:1)
    at memoized (c:\GIT\Pltfm\client\pltfm\node_modules\reselect\es\defaultMemoize.js:123:1)
    at selector (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\utils\createSelector.js:35:1)
    at <anonymous> (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\hooks\features\dimensions\useGridDimensions.js:50:1)
    at enhancedHandler (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\hooks\utils\useGridApiEventHandler.js:39:1)
    at emit (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\utils\EventManager.js:63:1)
    at <anonymous> (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\hooks\core\useGridApiInitialization.js:37:1)
    at apiRef.current.<computed> (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\hooks\utils\useGridApiMethod.js:14:1)
    at <anonymous> (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\hooks\features\sorting\useGridSorting.js:105:1)
    at apiRef.current.<computed> (c:\GIT\Pltfm\client\pltfm\node_modules\@mui\x-data-grid\hooks\utils\useGridApiMethod.js:14:1)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\GIT\Pltfm\client\pltfm\node_modules\.bin\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.898.0), Chromium (107.0.1418.42)
  npmPackages:
    @emotion/react: ^11.5.0 => 11.9.0
    @emotion/styled: ^11.3.0 => 11.8.1
    @mui/base:  5.0.0-alpha.100
    @mui/core-downloads-tracker:  5.10.8
    @mui/icons-material: ^5.10.6 => 5.10.6
    @mui/lab: ^5.0.0-alpha.98 => 5.0.0-alpha.98
    @mui/material: ^5.10.8 => 5.10.8
    @mui/private-theming:  5.10.6
    @mui/styled-engine: ^5.10.8 => 5.10.8
    @mui/styles: ^5.10.8 => 5.10.8
    @mui/system: ^5.10.8 => 5.10.8
    @mui/utils:  5.10.3
    @mui/x-data-grid:  5.17.12
    @mui/x-data-grid-generator: ^5.17.12 => 5.17.12
    @mui/x-data-grid-premium:  5.17.12
    @mui/x-data-grid-pro: 5.17.12 => 5.17.12
    @mui/x-date-pickers: 5.0.8 => 5.0.8
    @mui/x-date-pickers-pro: 5.0.8 => 5.0.8
    @mui/x-license-pro:  5.17.12
    @types/react: ^17.0.2 => 17.0.45
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.3.5 => 4.6.4
</details>

**Comment by gavbrennan** [comment]
Just to add, I was trying assign this function to column "A" in the example above so I tried to create a new column (call it "AB") and assign it there instead, to avoid any possible infinite looping, but it makes no difference and I still get the same call stack error.

**Comment by gavbrennan** [comment]
Tricky one, but I hope this demonstrates it - https://codesandbox.io/s/optimistic-smoke-wibwxm?file=/demo.tsx:3448-3473

I think disableRowGrouping being present is causing me the problem -  set it to disableRowGrouping={true} and it gives the callstack error, setting to false seems to work fine.

**Comment by gavbrennan** [comment]
Some more detail - i tried a work around, to disable the new grouping function if grouping was disabled on the grid.  However, this doesnt seem to work, beyond flipping the flag back and forth once, so there seems to be something stateful inside the grid causing this problem

**Comment by gavbrennan** [comment]
@m4theushw please advise if you can now reproduce?

**Comment by gavbrennan** [comment]
Apologies, I forgot the example sandbox was still pointing to the pre-release code.  I'll look out for the fix.
