### ISSUE TITLE
[data grid] When adding DataGridPremium, it is giving undefined prototype error in inherits browser 

### ISSUE THREAD

**Issue by fatih-mdous** [mui/mui-x#7032]
### Order ID 💳

#54980

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

The code is working properly with DataGridPro but when adding DataGridPremium, it is giving this error :
![Screen Shot 2022-11-28 at 11 25 10 AM](https://user-images.githubusercontent.com/79893620/204352572-088a0f0f-a87a-4a15-a48b-e425c6a9df3d.png)

### Your environment 🌎
![Screen Shot 2022-11-28 at 11 29 02 AM](https://user-images.githubusercontent.com/79893620/204353404-caffe4c6-3d3c-4111-9ca1-bc919c5cb992.png)
### Code
```
import * as React from 'react';

import {
  DataGridPremium,
  GridToolbar,
  useGridApiContext,
  useGridSelector,
  gridFilteredDescendantCountLookupSelector,
  useGridApiRef,
  gridVisibleSortedRowIdsSelector,
} from '@mui/x-data-grid-premium';

const DataGridTable = (props) => {
  const { columns = [], rows = [] } = props;

  return <DataGridPremium {...props} rows={rows} columns={columns} />;
};

export {
  DataGridTable,
  useGridApiContext,
  useGridSelector,
  gridFilteredDescendantCountLookupSelector,
  useGridApiRef,
  gridVisibleSortedRowIdsSelector,
};
```

**Comment by fatih-mdous** [comment]
I updated the code. How can I create this issue in Codesandbox? This is happening when applied Datagridpremium in our environment.

**Comment by fatih-mdous** [comment]
I updated https://codesandbox.io/s/data-grid-community-forked-21exr1?file=/src/DatagridTable.js:44-60. It is working fine. Does it could be related to licence key ?

**Comment by fatih-mdous** [comment]
Is there anybody to response about aws codeartifact problem for dataGridPremium?

**Comment by fatih-mdous** [comment]
Please let me know if you take care of this problem. I will inform tech lead about datagridpremium integration in our environment

**Comment by fatih-mdous** [comment]
@m4theushw I realized that when using "react-scripts": "4.0.3", datagridpremium is giving that error, it is not giving that error `inherits_browser.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.inherits (inherits_browser.js:5:1)
    at Module.<anonymous> (index.es.js:293169:1))` when using "react-scripts": "5.0.1".

**Comment by fatih-mdous** [comment]
@m4theushw  is this library(`@mui/x-license-pro`) for Datagridpremium too?

**Comment by fatih-mdous** [comment]
@m4theushw We solved the problem because
Removed makeStyles as it is incompatible with React >18
This is not good for MUI all feature should work all version. Shouldn't be any difference Datagridpro and Datagridpremium.
We had to change 102 pages in middle of development. This is frustrating

**Comment by michelengelen** [comment]
Closing this one out. As established in the thread, the error did not originate in the grid: it came from building with `react-scripts` 4 and the legacy `makeStyles` API, and disappeared with `react-scripts` 5 or after removing `makeStyles`. That combination is a bundler and legacy-styling compatibility problem, so there is no fix to ship on our side. The v5 packages involved are also end of life.

Closing as not planned. If a current version of `@mui/x-data-grid-premium` throws in a clean build setup, please open a new issue with a repository that reproduces the build.
