### ISSUE TITLE
Breaking change in V5.17.20 to V5.17.22 migration - Datagrid crashes in React portal

### ISSUE THREAD

**Issue by O-JB** [mui/mui-x#7875]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: No live example, but will provide extensive code below.

Steps:
1. Create a modal popout window using the module at the bottom here (I can verify that the bug is not caused directly by this code, as my datagrids render perfectly for @mui/x-data-grid v5.17.22.

2. Inside this modal popout window, attempt to render any datagrid (e.g., immediately below).

```
return (
    <Modal 
        title="Test"
        closeWindow={// generic callback function to unmount modal}
        features={{width: 1080, height: 800}}
    >
        // Child components here
    </Modal>
)
```

```
/**
 * Modal.tsx
 */

/**
 * Section 1 - Imports
 */

// React & Component Libraries
import React, { ReactNode } from 'react';
import { createPortal } from 'react-dom' 

// Node & TypeScript Libraries
import _ from "lodash";


/**
 * Section 2 - Helper functions & Typing:
 */

interface IWindowFeatures {
    height?: number,
    width?: number,
}

interface IModalProps {
    title: string,
    features: IWindowFeatures,
    children: ReactNode,                        
    closeWindow: () => void,
}

interface IModalState {
    features: IWindowFeatures,
    externalWindow: Window | null;
    containerElement: HTMLElement | null;
}

/**
 * Section 3 - Modal (Popout) Window
 */

/**
 * Modal - Basic component that will enable us to render components into custom 'Popout' windows.
 * 
 * Portals provide a first-class way to render children into a DOM node that exists outside the DOM hierarchy of the parent component.
 * Portals were introduced into React in v16+. More info here: https://reactjs.org/docs/portals.html.
 */
class Modal extends React.Component<IModalProps, IModalState> {
    constructor(props: IModalProps) {
        super(props);
        this.state = {
            features: this.props.features,
            externalWindow: null,
            containerElement: null
        };
    }

    /**
     * componentDidMount - When we create this component, open a new window. 
     * The render method will then mount child components into this new window.
     * 
     * Note that whilst this method should run only a single time, in React strict mode
     * it could run multiple times (generally twice). If this method runs twice, this component
     * does not render properly. We therefore include some apparently redundant code to handle
     * cases where the method has already been run.
     * 
     * Due to the identified complications in launching this popout modal, this section is broken
     * down into clear sections, with clear logs for debugging.
     */
    public async componentDidMount() {

        // Modal mount section 1:
        // ----------------------
        // If this method has already been run, we use the existing window object.
        // Otherwise, we attempt to create a new window, into which we will create a 
        // root division and React will mount our child content there.
        let externalWindow: Window | null;
        if (this.state.externalWindow instanceof Window) {
            externalWindow = this.state.externalWindow;
            console.log("Modal mount log - Section 1 - Window already exists on state, using this window.", externalWindow);
        } 

        else {
            externalWindow = window.open('', '', this.unpackWindowFeatures());
            await this.setState({ externalWindow: externalWindow });
            console.log("Modal mount log - Section 1 - Window does not yet exist. Creating and writing to state.", externalWindow);
        }

        // Error check 1 - If the modal window is still nullish, raise an error.
        if (!externalWindow) {
            console.error("Modal mount error - Section 1 - Window object is nullish.");
            return;
        }

        // Modal mount section 2:
        // ----------------------
        // Creating container element and writing to state. Note that like before, we need to make sure
        // that if this method is run twice, we are still able to use the same initially created root node.
        // If the method has already been run, the container element should exist in state.
        // Otherwise, create new root division into which child content can be rendered and write to state.
        let containerElement: HTMLElement | null;
        if (this.state.containerElement instanceof HTMLElement) {
            containerElement = this.state.containerElement;
            console.log("Modal mount log - Section 2 - Container element already exists on state, using this element.", containerElement);
        }


        else {
            containerElement = externalWindow.document.createElement('div');
            containerElement.id = "root";
            await this.setState({ containerElement: containerElement });

            console.log("Modal mount log - Section 2 - Container element does not yet exist. Creating and writing to state.", containerElement);
        }

        // Error check 2 - If the container element / modal root is still nullish, raise an error.
        if (!containerElement) {
            console.error("Modal mount error - Section 2 - Container element is nullish.");
            return;
        }

        // Modal mount section 3:
        // ----------------------
        // Configuration of document title and stylesheets. 
        // Create event listener to make sure the window closes when the component unloads.
        externalWindow.document.body.appendChild(containerElement);
        externalWindow.document.title = this.props.title;

        // Copy the app's styles into the new window.
        // Method found here: https://blog.scottlogic.com/2019/10/29/popout-windows-in-react.html
        const stylesheets = Array.from(document.styleSheets);
        for (let stylesheet of stylesheets) {
            const css = stylesheet as CSSStyleSheet;

            if (stylesheet.href) {
                const newStyleElement = document.createElement('link');
                newStyleElement.rel = 'stylesheet';
                newStyleElement.href = stylesheet.href;
                externalWindow.document.head.appendChild(newStyleElement);

            } else if (css && css.cssRules && css.cssRules.length > 0) {
                const newStyleElement = document.createElement('style');
                Array.from(css.cssRules).forEach(rule => {
                    newStyleElement.appendChild(document.createTextNode(rule.cssText));
                });
                externalWindow.document.head.appendChild(newStyleElement);
            }
        }

        // Make sure the window closes when the component unloads
        externalWindow.addEventListener('beforeunload', () => {
            this.props.closeWindow();
        });

        // In this method, we have configured the external window object, as well as the container element 
        // (a division inserted into the external window).
        // Here, we update these objects in state.
        await this.setState({
            externalWindow: externalWindow,
            containerElement: containerElement
        });

        console.log("Modal mount log - ComponentDidMount Completed, window & container as follows:", this.state.externalWindow, this.state.containerElement);
    }

    /**
     * unpackWindowFeatures - Helper function that parses input window features into string form for initialisation of the new window.
     * @returns {string}
     */
    private unpackWindowFeatures(): string {
        const features = this.state.features;
        return `width=${features?.width ?? 800}px, height=${features?.height ?? 500}px, left=300, top=200`;
    }

    /**
     * shouldComponentUpdate - React lifecycle method that we overwrite here to ensure it does not rerender too frequently.
     * @param {IModalProps} nextProps
     */
    
    componentDidUpdate(nextProps: IModalProps, nextState: IModalState) {
        return (!_.isEqual(nextProps, this.props)) || (!_.isEqual(nextState, this.state))
    }

    /**
     * componentWillUnmount - React lifecycle method which we override here to 
     *  make sure the window closes when the component unmounts.
     *  This method is always called when a component is being removed from the DOM.
     */
    componentWillUnmount() {
        if (this.state.externalWindow) {
            this.state.externalWindow.close();
        }
    }

    /**
     * Mount child components into the container element in the new window.
     */
    render(): JSX.Element | null {

        // Modal mount section 4:
        // ----------------------
        // We now want to render content into our container element.
        // If there is no container element to render the element into, we can't proceed with the render.
        if (!this.state.containerElement) {
            console.error("Modal mount error - Section 4 - Nullish container element.", this.state.containerElement);
            return null;
        }

        // Render this component's children into the root element of the popout window
        // The first argument (child) is any renderable React child, such as an element, string, or fragment. 
        // The second argument (container) is a DOM element.
        console.log("Modal mount log - Section 4 - Rendering content into container element.", this.props.children, this.state.containerElement);
        return createPortal(this.props.children, this.state.containerElement);
    }
}

export default Modal;
```

### Current behavior 😯

I click a button in my application, causing its parent's state to change such that the modal popout window is launched (with my components of interest passed into this window as children). 
My popout window immediately crashes, because it appears that when the datagrid is initialising, under the hood it is attempting to add a resize listener to itself, and a breaking change is exposed. I have done all I can to find where this going wrong and I am confident that I have found the line causing the problem.

Lets begin with the stack trace: **(I am unable to upload images to GH... here is the text)**

Trace 1:
> TypeError: root.getElementById is not a function
>     at createStyles (index.js:80:1)
>     at Object.addResizeListener (index.js:105:1)
>     at GridAutoSizer.js:65:1
>     at commitHookEffectListMount (react-dom.development.js:23150:1)
>     at commitLayoutEffectOnFiber (react-dom.development.js:23268:1)
>     at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
>     at commitLayoutEffects_begin (react-dom.development.js:24674:1)
>     at commitLayoutEffects (react-dom.development.js:24612:1)
>     at commitRootImpl (react-dom.development.js:26823:1)
>     at commitRoot (react-dom.development.js:26682:1)

Trace 2:

> The above error occurred in the <ForwardRef(AutoSizer)> component:
> 
>     at AutoSizer (http://localhost:3000/static/js/bundle.js:51589:7)
>     at div
>     at http://localhost:3000/static/js/bundle.js:17724:66
>     at GridMainContainer (http://localhost:3000/static/js/bundle.js:56329:100)
>     at GridBody (http://localhost:3000/static/js/bundle.js:52816:5)
>     at div
>     at http://localhost:3000/static/js/bundle.js:17724:66
>     at GridRoot (http://localhost:3000/static/js/bundle.js:56491:100)
>     at GridContextProvider (http://localhost:3000/static/js/bundle.js:61694:5)
>     at DataGrid (http://localhost:3000/static/js/bundle.js:49614:84)
>     at DataGridWrapperFC (http://localhost:3000/static/js/bundle.js:8268:82)
>     at ErrorBoundary (http://localhost:3000/static/js/bundle.js:1189:5)
>     at div
>     at div
>     at div
>     at CurveEditor (http://localhost:3000/static/js/bundle.js:7511:5)
>     at Modal (http://localhost:3000/main.0cb5c15af48216a178b3.hot-update.js:53:5)

Perhaps more usefully, is the line referenced by the stack trace which is exposing the bug:
(Note that the bottom function is called first, and it calls the ‘createStyles’ function. It is line 80 which I imagine exposes that ‘root’ is undefined).

(Again, unable to upload images to GH, sorry)

This is two functions from index.js in "node_modules\@mui\x-data-grid\lib\createDetectElementResize" , lines 79 to 125. The key line is line 80 (the second line of this snippet).

```
  var createStyles = function createStyles(doc, root) {
    if (!root.getElementById('muiDetectElementResize')) {    // <-------------This line
      //opacity:0 works around a chrome bug https://code.google.com/p/chromium/issues/detail?id=286360
      var css = (animationKeyframes ? animationKeyframes : '') + '.Mui-resizeTriggers { ' + (animationStyle ? animationStyle : '') + 'visibility: hidden; opacity: 0; } ' + '.Mui-resizeTriggers, .Mui-resizeTriggers > div, .contract-trigger:before { content: " "; display: block; position: absolute; top: 0; left: 0; height: 100%; width: 100%; overflow: hidden; z-index: -1; } .Mui-resizeTriggers > div { background: #eee; overflow: auto; } .contract-trigger:before { width: 200%; height: 200%; }',
        container = root.constructor.name === 'ShadowRoot' ? root : doc.head || doc.getElementsByTagName('head')[0],
        style = doc.createElement('style');
      style.id = 'muiDetectElementResize';
      style.type = 'text/css';
      if (nonce != null) {
        style.setAttribute('nonce', nonce);
      }
      if (style.styleSheet) {
        style.styleSheet.cssText = css;
      } else {
        style.appendChild(doc.createTextNode(css));
      }
      container.appendChild(style);
    }
  };
  var addResizeListener = function addResizeListener(element, fn) {
    if (!element.__resizeTriggers__) {
      var doc = element.ownerDocument;
      var elementStyle = hostWindow.getComputedStyle(element);
      if (elementStyle && elementStyle.position == 'static') {
        element.style.position = 'relative';
      }
      createStyles(doc, element.getRootNode());
      element.__resizeLast__ = {};
      element.__resizeListeners__ = [];
      (element.__resizeTriggers__ = doc.createElement('div')).className = 'Mui-resizeTriggers';
      element.__resizeTriggers__.innerHTML = '<div class="expand-trigger"><div></div></div>' + '<div class="contract-trigger"></div>';
      element.appendChild(element.__resizeTriggers__);
      resetTriggers(element);
      element.addEventListener('scroll', scrollListener, true);

      /* Listen for a css animation to detect element display/re-attach */
      if (animationstartevent) {
        element.__resizeTriggers__.__animationListener__ = function animationListener(e) {
          if (e.animationName == animationName) {
            resetTriggers(element);
          }
        };
        element.__resizeTriggers__.addEventListener(animationstartevent, element.__resizeTriggers__.__animationListener__);
      }
    }
    element.__resizeListeners__.push(fn);
  };
```

### Expected behavior 🤔

When using the v5.17.22 datagrid, when a new popup window is opened, my datagrids render perfectly, and do not crash.

### Context 🔦

I am attempting to migrate an existing project from MUI datagrid V5 to V6, and in this project I have the occasional datagrid rendered in modal popout windows. These datagrids worked perfectly before the migration, but now crash my popout windows when launched.

### Your environment 🌎

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.86)
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.107
    @mui/core-downloads-tracker:  5.10.15
    @mui/icons-material: ^5.11.0 => 5.11.0
    @mui/material: ^5.10.15 => 5.10.15
    @mui/private-theming:  5.10.15
    @mui/styled-engine:  5.10.14
    @mui/system:  5.10.15
    @mui/types:  7.2.1
    @mui/utils:  5.11.7
    @mui/x-data-grid: ^6.0.0-beta.2 => 6.0.0-beta.2
    @mui/x-date-pickers: ^5.0.13 => 5.0.13
    @types/react: ^18.0.25 => 18.0.25
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.3 => 4.9.3
```

**Comment by O-JB** [comment]
Unable to update my initial report. I have done some further digging and the issue actually arises between v5.17.20 and v5.17.21 (I must have been on 5.17.20 as opposed to 5.17.22). 
I think the issue was introduced alongside this story: Fix scrolling on resize for data grids inside shadow root #7298 , in that MUI can't find a root node to append resize styles to if the datagrid is launched in a popout React portal.
I have changed the issue title accordingly (but please note that this issue does still manifest in the v6 version quoted in my initial report).
Many thanks

**Comment by cherniavskii** [comment]
@O-JB Can you provide a minimal reproduction example for this issue?

**Comment by O-JB** [comment]
@cherniavskii Will do, will try and post something in the next 48 hours, thanks

**Comment by O-JB** [comment]
Hi @cherniavskii , my apologies for the delay in getting back to you. Here is a minimal reproduction for this issue. What I have done here is:

1. Use the 'npx create-react-app my-app --template typescript' command to build a boilerplate Typescript enabled React app.
2. Updated the package such that it contains the following:

```
  "dependencies": {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@mui/material": "^5.10.15",
    "@mui/x-data-grid": "^5.17.22",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/lodash": "^4.14.191",
    "@types/material-ui": "^0.21.12",
    "@types/node": "^16.18.12",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "lodash": "^4.17.21",
    "package": "^1.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
```

3. Overwritten the App.tsx file with the following code. There is a button that toggles whether or not the modal is in use, and I attempt to render a simple Datagrid inside the modal when appropriate. The Datagrid render fails. Hopefully this is enough for you to reproduce the bug?

```
/**
 * App.tsx
 */

/**
 * Section 1 - Imports
 */
import React, { ReactNode } from 'react';
import logo from './logo.svg';
import './App.css';
import { createPortal } from 'react-dom'; 
import _ from "lodash";
import { Box, Button } from '@mui/material';
import { DataGrid, GridColDef } from '@mui/x-data-grid';

/**
 * Section 2 - App Component:
 */
interface IAppProps {}
interface IAppState {
    showModal: boolean,
}


export default class App extends React.Component<IAppProps, IAppState> {
    constructor(props: IAppProps) {
        super(props);
        this.state = {
            showModal: false,
        }
    }

    render() {
        return (
            <div className="App">
                <header className="App-header">
                    <img src={logo} className="App-logo" alt="logo" />
                    {
                        (this.state.showModal) ? (
                            <Modal
                                title="Popout Window"
                                closeWindow={() => {this.setState({showModal: false})}}
                            >
                                <ModalContent />
                            </Modal>
                        ) : (
                            <></>
                        )
                    }
                    <Button 
                        variant="contained"
                        onClick={() => {this.setState((prevState) => ({
                            showModal: !prevState.showModal
                        }))}}
                    >
                        Toggle Modal
                    </Button> 
                </header>
            </div>
        );
    }
}

/**
 * Section 3 - Modal Component:
 */

interface IModalProps {
    title: string,
    children: ReactNode,                        
    closeWindow: () => void,
}

interface IModalState {
    externalWindow: Window | null;
    containerElement: HTMLElement | null;
}

class Modal extends React.Component<IModalProps, IModalState> {
    constructor(props: IModalProps) {
        super(props);
        this.state = {
            externalWindow: null,
            containerElement: null
        };
    }

    /**
     * componentDidMount - When we create this component, open a new window. 
     * The render method will then mount child components into this new window.
     */
    public async componentDidMount() {

        // Modal mount section 1:
        // ----------------------
        // If this method has already been run, we use the existing window object.
        // Otherwise, we attempt to create a new window, into which we will create a 
        // root division and React will mount our child content there.
        let externalWindow: Window | null;
        if (this.state.externalWindow instanceof Window) {
            externalWindow = this.state.externalWindow;
            console.log("Modal mount log - Section 1 - Window already exists on state, using this window.", externalWindow);
        } 

        else {
            externalWindow = window.open('', '', `width=800px, height=500px, left=300, top=200`);
            await this.setState({ externalWindow: externalWindow });
            console.log("Modal mount log - Section 1 - Window does not yet exist. Creating and writing to state.", externalWindow);
        }

        // Error check 1 - If the modal window is still nullish, raise an error.
        if (!externalWindow) {
            console.error("Modal mount error - Section 1 - Window object is nullish.");
            return;
        }

        // Modal mount section 2:
        // ----------------------
        // Creating container element and writing to state. Note that like before, we need to make sure
        // that if this method is run twice, we are still able to use the same initially created root node.
        // If the method has already been run, the container element should exist in state.
        // Otherwise, create new root division into which child content can be rendered and write to state.
        let containerElement: HTMLElement | null;
        if (this.state.containerElement instanceof HTMLElement) {
            containerElement = this.state.containerElement;
            console.log("Modal mount log - Section 2 - Container element already exists on state, using this element.", containerElement);
        }


        else {
            containerElement = externalWindow.document.createElement('div');
            containerElement.id = "root";
            await this.setState({ containerElement: containerElement });

            console.log("Modal mount log - Section 2 - Container element does not yet exist. Creating and writing to state.", containerElement);
        }

        // Error check 2 - If the container element / modal root is still nullish, raise an error.
        if (!containerElement) {
            console.error("Modal mount error - Section 2 - Container element is nullish.");
            return;
        }

        // Modal mount section 3:
        // ----------------------
        // Configuration of document title and stylesheets. 
        // Create event listener to make sure the window closes when the component unloads.
        externalWindow.document.body.appendChild(containerElement);
        externalWindow.document.title = this.props.title;

        // Copy the app's styles into the new window.
        // Method found here: https://blog.scottlogic.com/2019/10/29/popout-windows-in-react.html
        const stylesheets = Array.from(document.styleSheets);
        for (let stylesheet of stylesheets) {
            const css = stylesheet as CSSStyleSheet;

            if (stylesheet.href) {
                const newStyleElement = document.createElement('link');
                newStyleElement.rel = 'stylesheet';
                newStyleElement.href = stylesheet.href;
                externalWindow.document.head.appendChild(newStyleElement);

            } else if (css && css.cssRules && css.cssRules.length > 0) {
                const newStyleElement = document.createElement('style');
                Array.from(css.cssRules).forEach(rule => {
                    newStyleElement.appendChild(document.createTextNode(rule.cssText));
                });
                externalWindow.document.head.appendChild(newStyleElement);
            }
        }

        // Make sure the window closes when the component unloads
        externalWindow.addEventListener('beforeunload', () => {
            this.props.closeWindow();
        });

        // In this method, we have configured the external window object, as well as the container element 
        // (a division inserted into the external window).
        // Here, we update these objects in state.
        await this.setState({
            externalWindow: externalWindow,
            containerElement: containerElement
        });

        console.log("Modal mount log - ComponentDidMount Completed, window & container as follows:", this.state.externalWindow, this.state.containerElement);
    }

    /**
     * shouldComponentUpdate - React lifecycle method that we overwrite here to ensure it does not rerender too frequently.
     * @param {IModalProps} nextProps
     */
    
    componentDidUpdate(nextProps: IModalProps, nextState: IModalState) {
        return (!_.isEqual(nextProps, this.props)) || (!_.isEqual(nextState, this.state))
    }

    /**
     * componentWillUnmount - React lifecycle method which we override here to 
     *  make sure the window closes when the component unmounts.
     *  This method is always called when a component is being removed from the DOM.
     */
    componentWillUnmount() {
        if (this.state.externalWindow) {
            this.state.externalWindow.close();
        }
    }

    /**
     * Mount child components into the container element in the new window.
     */
    render(): JSX.Element | null {

        // Modal mount section 4:
        // ----------------------
        // We now want to render content into our container element.
        // If there is no container element to render the element into, we can't proceed with the render.
        if (!this.state.containerElement) {
            console.error("Modal mount error - Section 4 - Nullish container element.", this.state.containerElement);
            return null;
        }

        // Render this component's children into the root element of the popout window
        // The first argument (child) is any renderable React child, such as an element, string, or fragment. 
        // The second argument (container) is a DOM element.
        console.log("Modal mount log - Section 4 - Rendering content into container element.", this.props.children, this.state.containerElement);
        return createPortal(this.props.children, this.state.containerElement);
    }
}

/**
 * Section 4 - Modal Content:
 */

function ModalContent() {
    const columns: GridColDef[] = [
        { field: 'firstName', headerName: 'First name', width: 130 },
        { field: 'lastName', headerName: 'Last name', width: 130 },
        {
            field: 'fullName',
            headerName: 'Full name',
            width: 160,
            valueGetter: params => `${params.row.firstName || ''} ${params.row.lastName || ''}`,
        },
    ];
    const rows = [
        { id: 1, lastName: 'Snow', firstName: 'Jon' },
        { id: 2, lastName: 'Lannister', firstName: 'Cersei' },
        { id: 3, lastName: 'Lannister', firstName: 'Jaime' },
        { id: 4, lastName: 'Stark', firstName: 'Arya' },
        { id: 5, lastName: 'Targaryen', firstName: 'Daenerys' },
    ];
    return (
        <DataGrid rows={rows} columns={columns} />
    );
}
```

**Comment by cherniavskii** [comment]
Hi @O-JB 
Thanks for the details!
I created this codesandbox with the code you provided: https://codesandbox.io/s/upbeat-browser-c18b3v?file=/demo.tsx

However, I tried rewriting the `Modal` component with React hooks to simplify it a bit and it doesn't crash anymore:
https://codesandbox.io/s/confident-star-c2pmbs?file=/demo.tsx

But the problem is that the styles are missing in the popup window. Copying the stylesheets from the parent window doesn't really worn with CSS in JS libraries (we use Emotion). This is basically the same problem that you would have when using the MUI components in a Shadow DOM. We have a Shadow DOM guide that covers this use case - see https://mui.com/material-ui/guides/shadow-dom/

Given the guide above, I used Emotion's CacheProvider to make sure the popup window has the necessary styles and everything seems to work with this approach - see this demo: https://codesandbox.io/s/awesome-leakey-yvubp2?file=/demo.tsx

Does this solve your issue?

**Comment by O-JB** [comment]
Hi @cherniavskii, I really appreciate the time you have taken to look into this in such detail. I hope to integrate your changes into my project in the next 24 hours, I will let you know ASAP if this solves the problem so that the ticket can be closed (and my apologies that the issue was likely with my code as opposed to MUI).

**Comment by cherniavskii** [comment]
Great to hear that!
Did you find out what was the cause of the issue?
