### ISSUE TITLE
[data grid][question] Please can someone give further details on #7594

### ISSUE THREAD

**Issue by mbiggs-gresham** [mui/mui-x#8062]
### Order ID 💳

45466

### The problem in depth 🔍

We have put extensive work in to using dayjs objects for our Date and DateTime columns and have developed a framework around it. We store dayjs objects in an apollo graphql cache for performance so that we aren't creating endless dayjs objects at the point of rendering due to us using infinite scrolling. (eg minimising the lag when more data is fetched).

We're quite worried about the change described in https://github.com/mui/mui-x/pull/7594 as only supporting Date objects now. We don't use the grids built in filtering/sorting or searching as we set these to server side and rolled our own. We do have our own cell renderer that does various things with the dayjs objects. We need dayjs objects as we also perform quite extensive formatting of date values for various locales etc. 

Please can someone give more details and let me know if this is going to completely break using the grid for us?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by mbiggs-gresham** [comment]
I can't share most of the code unfortunately.

We have quite a few components alongside the grid such as a free text searchbar etc that all use the type of the column to offer various things such as date pickers etc if it's a `date` or `dateTime`. When you say create our own custom type do you mean we won't be able to use those two anymore?

In terms of the grid itself, we don't set a custom cell formatter on it, we literally only set a custom cell renderer that then assumes the `value` on the `GridRenderCellParams` is a dayjs object. 

I'm assuming the grid itself won't really care that it is a dayjs object then (eg it doesn't directly try to do anything with a `Date` object? We are more or less bypassing the actual type and just doing our own thing and this change shouldn't be an issue?

**Comment by mbiggs-gresham** [comment]
Having looked in to upgrading to v6 I can confirm that this does indeed break things for us with the following error

`gridDateColDef.js:13 Uncaught Error: MUI: `dateTime` column type only accepts `Date` objects as values.
Use `valueGetter` to transform the value into a `Date` object.
Row ID: 642567ad06d4d237e207153b, field: "ctc.friska.investigation.repotosource.standard.CreatedDateTime".
    at throwIfNotDateObject (gridDateColDef.js:13:11)
    at Object.gridDateTimeFormatter [as valueFormatter] (gridDateColDef.js:40:3)
    at useGridParamsApi.js:81:38
    at Object.getCellParams (useGridApiMethod.js:14:20)
    at GridRow.js:193:39
    at GridRow2 (GridRow.js:323:20)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)`

Changing the underlying object type for us would then cause us further issues with other aspects of the application. Switching to our own date and dateTime data types seems like the only way around this but I have no idea if that will cause other problems. It appears to render OK, just throwing that error is obviously not good. 

Are there any plans to support other date libraries like the date pickers do? They have dayjs adapters/wrappers (which we also use in our same components).

**Comment by mwardGresham** [comment]
Any updates on this?

**Comment by michelengelen** [comment]
Closing this one out, since the v6 migration is long settled and the behavior is unchanged in current versions: `date` and `dateTime` columns require `Date` instances (#7594). The supported way to keep dayjs objects in your rows is to convert at the column boundary and keep your renderer reading the row:

```tsx
{
  field: 'createdAt',
  type: 'dateTime',
  valueGetter: (value) => value?.toDate(),
  renderCell: (params) => myFormat(params.row.createdAt), // still dayjs
}
```

Sorting, filtering, and column-type integrations then work against real `Date`s while your formatting stays on dayjs.

Closing as answered. If the conversion breaks something on the latest version, please open a new issue with a reproduction.
