### ISSUE TITLE
Codemod failures on Toolpad repo

### ISSUE THREAD

**Issue by Janpot** [mui/mui-x#8264]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Run the codemod `v6.0.0/preset-safe` on https://github.com/mui/mui-toolpad/blob/d7fb0f17b81083e7e98899a9fccfc40b9f9ab0fe/packages/toolpad-components/src/DataGrid.tsx
2. Observe error:
```
 ERR /Users/janpotoms/Projects/toolpad/packages/toolpad-components/src/DataGrid.tsx Transformation error (Cannot read properties of undefined (reading 'name'))
TypeError: Cannot read properties of undefined (reading 'name')
    at find (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/util/removeObjectProperty.js:17:102)
    at Array.find (<anonymous>)
    at NodePath.<anonymous> (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/util/removeObjectProperty.js:17:69)
    at /Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/node_modules/jscodeshift/src/Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/node_modules/jscodeshift/src/Collection.js:74:18)
    at removeObjectProperty (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/util/removeObjectProperty.js:16:6)
    at forEach (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/index.js:20:38)
    at Array.forEach (<anonymous>)
    at transformer (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/index.js:19:12)
```

### Current behavior 😯

Codemod throws an error

### Expected behavior 🤔

Codemod modifies the file

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
The erros is in `removeObjectProperty` If the prop you are looking for does not exist and there is a prop spreading, `targetAttribute` fails, because it goes up to `{...props}` attributes for which `name` is not defined

```jsx
// Pass
<DataGridPro
  experimentalFeatures={{
    newEditingApi: true,
    rowPinning: true,
  }}
  {...props}
/>

// Fail
<DataGridPro {...props} />
```
