### ISSUE TITLE
[data grid] Wrap default grid cell behaviour with tooltip and renderCell

### ISSUE THREAD

**Issue by benosmond** [mui/mui-x#9232]
### Order ID or Support key 💳 (optional)

#59960

### The problem in depth 🔍

I am trying to wrap certain grid cells in a tooltip in order to display an error/warning message, and I'm using `renderCell` to do this. The problem is that aside from wrapping certain cells in a tooltip, I just want the default behaviour - I don't want to implement anything custom.

The documentation tells me that the default component is `<GridCell />` but I've been unable to successfully use it. First I tried the below which I saw in a similar issue on SO works with `renderEditCell`:

```tsx
renderCell(params: GridRenderCellParams) {
    return <GridCell { ...params } />;
}
```

This gives me an error I don't really understand:

> MUI: `capitalize(string)` expects a string argument.
    at capitalize (http://localhost:12345/static/js/bundle.js:59164:11)
    at useUtilityClasses (http://localhost:12345/static/js/bundle.js:73578:87)
    at http://localhost:12345/static/js/bundle.js:73629:19
    at renderWithHooks (http://localhost:12345/static/js/bundle.js:130814:22)
    at updateForwardRef (http://localhost:12345/static/js/bundle.js:132647:24)
    at beginWork (http://localhost:12345/static/js/bundle.js:134387:20)
    at HTMLUnknownElement.callCallback (http://localhost:12345/static/js/bundle.js:121389:18)
    at Object.invokeGuardedCallbackDev (http://localhost:12345/static/js/bundle.js:121433:20)
    at invokeGuardedCallback (http://localhost:12345/static/js/bundle.js:121488:35)
    at beginWork$1 (http://localhost:12345/static/js/bundle.js:138484:11)

I get the above error also when I try to just chuck in an empty cell:

```tsx
renderCell(params: GridRenderCellParams) {
    return <GridCell />;
}
```

The Intellisense says the `<GridCell />` component takes `GridCellProps`, so I tried providing just the `value` and `formattedValue` from that interface:

```tsx
renderCell(params: GridRenderCellParams) {
    return <GridCell
        value={value}
        formattedValue={formattedValue} />
}
```

This also gives errors:
> Cannot find name 'value'.
> Cannot find name 'formattedValue'.

What I want is for the majority of cells in the grid to behave exactly as they would without `renderCell`, and a handful to be wrapped in a tooltip.
I also want the tooltip to cover the whole cell, not just the content inside, so it shows when any part of the cell is hovered.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.90
    Edge: Spartan (44.22000.120.0), Chromium (113.0.1774.35)
  npmPackages:
    @emotion/react:  11.10.6
    @emotion/styled:  11.10.6
    @mui/base:  5.0.0-alpha.96
    @mui/core-downloads-tracker:  5.12.2
    @mui/icons-material:  5.11.16
    @mui/lab: ^5.0.0-alpha.98 => 5.0.0-alpha.98
    @mui/material: ^5.10.15 => 5.12.2
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/system:  5.12.1
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-data-grid:  6.3.0
    @mui/x-data-grid-premium: ^6.3.0 => 6.3.0
    @mui/x-data-grid-pro:  6.3.0
    @mui/x-date-pickers:  5.0.20
    @mui/x-license-pro: ^6.0.0-beta.3 => 6.0.4
    @types/react: ^18.0.21 => 18.2.0
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.8.4 => 4.9.5
```
</details>

**Comment by MBilalShafi** [comment]
Have you already checked this demo if it fulfills your need? https://mui.com/x/react-data-grid/components/#cell

It uses `onMouseEnter` and `onMouseLeave` events exposed by the `<GridCell />` to place a Tooltip using `<Popover />` component next to each cell.

Does a similar implementation work in your case?

**Comment by benosmond** [comment]
> Have you already checked this demo if it fulfills your need? https://mui.com/x/react-data-grid/components/#cell

From what I can see the panel that shows on mouse over in that demo behaves very differently from the `<Tooltip />` component. If it's possible to use the same approach with a `<Tooltip />` or make `<Popover />` behave the way I want then I could use that, but otherwise I think I need `renderCell`.

**Comment by yehudamakarov** [comment]
also wondering how to add additional functionality inside of `renderCell` based on the cell's default component, instead of needing to implement my own from the ground up

**Comment by benosmond** [comment]
> also wondering how to add additional functionality inside of `renderCell` based on the cell's default component, instead of needing to implement my own from the ground up

In the end, I had to look at the DOM and try to replicate what the 'default' cell looked like as much as I could.

It seems to be a `<div>` element with an MUI class attached, and then whatever value the cell has goes directly inside. I imported the `gridClasses` object from `@mui/x-data-grid-premium` and then set up a 'default' `renderCell` like so:
```typescript
renderCell: ({ value, formattedValue }) => <div className={gridClasses.cellContent} 
    title={formattedValue ?? value.toString()}>
        {formattedValue ?? value.toString()}
</div>;
```

I found this behaves pretty much identically to the grid without `renderCell`, and then I could expand the function to conditionally wrap the cell in a tooltip, only render certain cells differently etc.
