### ISSUE TITLE
[DataGrid] Header filters warning: React does not recognize the `InputLabelProps` prop on a DOM element

### ISSUE THREAD

**Issue by romgrk** [mui/mui-x#9335]
### Steps to reproduce 🕹

https://codesandbox.io/s/affectionate-liskov-3vqysg?file=/demo.tsx

### Current behavior 😯

This warning is logged to the console:

```
Warning: React does not recognize the `InputLabelProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputlabelprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at eval (https://3vqysg.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at InputBase (https://3vqysg.csb.app/node_modules/@mui/material/InputBase/InputBase.js:185:43)
    at Input (https://3vqysg.csb.app/node_modules/@mui/material/Input/Input.js:108:43)
    at eval (https://3vqysg.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at Select (https://3vqysg.csb.app/node_modules/@mui/material/Select/Select.js:54:43)
    at div
    at eval (https://3vqysg.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at FormControl (https://3vqysg.csb.app/node_modules/@mui/material/FormControl/FormControl.js:62:43)
    at div
    at eval (https://3vqysg.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at GridFilterInputBoolean (https://3vqysg.csb.app/node_modules/@mui/x-data-grid/components/panel/filterPanel/GridFilterInputBoolean.js:37:16)
    at div
    at eval (https://3vqysg.csb.app/node_modules/@mui/x-data-grid-pro/components/headerFiltering/GridHeaderFilterCell.js:46:20)
    [cropped]
```

### Expected behavior 🤔

No warning

### Your environment 🌎

v6.7.0

**Comment by cbichis** [comment]
I confirm the issue. I am using data grid pro 6.11.1 and still getting the same issue.
