### ISSUE TITLE
Can't change defaultValue or value in TimePicker Component - Uncaught runtime error - MUI React

### ISSUE THREAD

**Issue by lucasnatanmelo** [mui/mui-x#9751]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
[codesandbox](https://codesandbox.io/embed/wonderful-tree-ww4m87?fontsize=14&hidenavigation=1&theme=dark)
Steps:

1. Initial Value is set on useState.
2. User try to change the value in TimePicker component.
3. An Uncaught runtime error is catch.

### Current behavior 😯

An Uncaught runtime error is catch when user tries to change value in TimePicker when a initial value is set.

### Expected behavior 🤔

Change the value properly of TimePicker component and control the value in useState.

### Context 🔦

I'm having a problem when I try to change the value manually of TimePicker component. The defaultValue and value are shown properly when set the initial value is set in useState, but when the user try to change the value in UI, an Uncaught runtime error is catch in the window.

Here's the error
ERROR
value.set is not a function
TypeError: value.set is not a function
    at AdapterDayjs.setMinutes (http://localhost:3000/static/js/bundle.js:26388:20)
    at transferDateSectionValue (http://localhost:3000/static/js/bundle.js:34391:22)
    at http://localhost:3000/static/js/bundle.js:34417:12
    at Array.reduce (<anonymous>)
    at mergeDateIntoReferenceDate (http://localhost:3000/static/js/bundle.js:34415:115)
    at updateSectionValue (http://localhost:3000/static/js/bundle.js:35066:101)
    at http://localhost:3000/static/js/bundle.js:33605:11
    at http://localhost:3000/static/js/bundle.js:25372:23
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:53134:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:53178:20)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Google Chrome
  
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.18.2 - C:\Program Files\nodejs\node.EXE        
    Yarn: Not Found
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (114.0.1823.82)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.7
    @mui/core-downloads-tracker:  5.14.0
    @mui/material: ^5.14.0 => 5.14.0
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/styled-engine-sc: ^5.12.0 => 5.12.0
    @mui/system:  5.14.0
    @mui/types:  7.2.4
    @mui/utils:  5.13.7
    @mui/x-date-pickers: ^6.10.0 => 6.10.0
    @types/react: ^18.2.14 => 18.2.14
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^6.0.4 => 6.0.4
    typescript: ^4.9.5 => 4.9.5

```
</details>

**Comment by lucasnatanmelo** [comment]
I found a solution using dayjs module and it worked. Here's the solution for who has this issue too.

import dayjs from 'dayjs';

const initialTime = dayjs().set('hour', 11).set('minute', 45).set('second', 23); // use set function to manual date changing
const [selectedTime, setSelectedTime] = useState(dayjs(initialTime));
