### ISSUE TITLE
[DatePicker] TypeError: pt.isUTC is not a function

### ISSUE THREAD

**Issue by cardotrejos** [mui/mui-x#9934]
Getting a weird error on the dayjs adapter. Here is the complete error

```
TypeError: pt.isUTC is not a function
    at AdapterDayjs.getTimezone (AdapterDayjs.js:300:1)
    at AdapterDayjs.setTimezone (AdapterDayjs.js:312:1)
    at Object.setTimezone (valueManagers.js:29:1)
    at useValueWithTimezone.js:29:1
    at Object.useMemo (react-dom.production.min.js:172:1)
    at react_production_min.useMemo (react.production.min.js:23:24)
    at useValueWithTimezone (useValueWithTimezone.js:29:1)
    at usePickerValue (usePickerValue.js:184:1)
    at usePicker (usePicker.js:21:1)
    at useDesktopPicker (useDesktopPicker.js:60:1)
    at DesktopDateTimePicker.js:86:1
    at Ch (react-dom.production.min.js:157:1)
    at gi (react-dom.production.min.js:176:1)
    at ck (react-dom.production.min.js:271:1)
    at bk (react-dom.production.min.js:250:1)
    at ak (react-dom.production.min.js:250:1)
    at Tj (react-dom.production.min.js:250:1)
    at Lj (react-dom.production.min.js:243:1)
    at react-dom.production.min.js:123:1
    at at.unstable_runWithPriority (scheduler.production.min.js:17:1)
    at gg (react-dom.production.min.js:122:1)
    at jg (react-dom.production.min.js:123:1)
    at ig (react-dom.production.min.js:122:1)
    at Jg (react-dom.production.min.js:237:1)
    at Oh (react-dom.production.min.js:170:1)
    at SlackEmployeesContext.jsx:23:1
    at AuthContext.jsx:94:1
```
    
   The weird thing is that the error it's only happening on the production environment. Any suggestions?
   
   (I don't know if it's related to this but I'm using Vite)

**Comment by alexfauquette** [comment]
Did you import the dayjs utc extension?

The error seems to come from those line.  which indicate you provided a DayJs value which does not have `isUTC` method.

https://github.com/mui/mui-x/blob/daaaf71f9811d0f21fd44220dc89e9a6f05557f6/packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts/#L326-L329


I can not do much without a minimal reproduction example of the bug. A codesandbox such as this one could be a good start:
https://codesandbox.io/s/fgsmg6?file=/Demo.tsx

**Comment by undesicimo** [comment]
@alexfauquette where are we supposed to extend dayjs in this case? Is it where the LocalizationProvider is set?

**Comment by alexfauquette** [comment]
For me it's were it makes the most sense

If with the information described in https://mui.com/x/react-date-pickers/timezone/#usage-with-day-js

Please consider opening an issue with the stackblitz or codesandbox reproducing the error such that we can better understand and answer your issue
